In [1]:
import numpy as np
import torch

In [2]:
input_data=np.array([[32,55,77],
                    [31,75,57],
                    [52,55,77],
                    [22,100,87],
                    [62,80,77]], dtype='float32')

In [3]:
input_data

array([[ 32.,  55.,  77.],
       [ 31.,  75.,  57.],
       [ 52.,  55.,  77.],
       [ 22., 100.,  87.],
       [ 62.,  80.,  77.]], dtype=float32)

In [4]:
target=np.array([[32,66],
                [52,76],
                [102,155],
                [32,26],
                [99,100]],dtype='float32')

In [6]:
#Convert numpy tp tensor
inputs=torch.from_numpy(input_data)
targets=torch.from_numpy(target)
print(inputs)
print(targets)

tensor([[ 32.,  55.,  77.],
        [ 31.,  75.,  57.],
        [ 52.,  55.,  77.],
        [ 22., 100.,  87.],
        [ 62.,  80.,  77.]])
tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])


In [7]:
# Initialize weights and bias
w=torch.randn(2,3, requires_grad=True)
b=torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.1390,  0.8235,  0.7681],
        [-0.1936,  0.3932, -0.9366]], requires_grad=True)
tensor([-0.4080, -0.4927], requires_grad=True)


In [11]:
def model(x):
    return x @ w.t() + b

In [12]:
pred=model(inputs)
print(pred)

tensor([[ 99.5853, -57.1817],
        [100.8325, -30.3909],
        [ 96.8051, -61.0528],
        [145.7165, -46.9181],
        [116.0036, -53.1581]], grad_fn=<AddBackward0>)


In [13]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])

In [14]:
### Loss
def MSE(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [15]:
loss=MSE(pred, targets)
print(loss)

tensor(12214.5957, grad_fn=<DivBackward0>)


In [16]:
# Compute the gradient
loss.backward()

In [17]:
print(w)
print(w.grad)

tensor([[-0.1390,  0.8235,  0.7681],
        [-0.1936,  0.3932, -0.9366]], requires_grad=True)
tensor([[  1392.4779,   3965.1702,   3758.0256],
        [ -5914.9355,  -9236.3340, -10064.4766]])


In [20]:
with torch.no_grad():
    w -=w.grad * 1e-5
    b -=b.grad * 1e-5

In [21]:
print(w)

tensor([[-0.1529,  0.7839,  0.7306],
        [-0.1344,  0.4856, -0.8360]], requires_grad=True)


In [22]:
print(b)

tensor([-0.4085, -0.4914], requires_grad=True)


In [24]:
pred=model(inputs)

In [26]:
loss=MSE(pred, targets)
print(loss)

tensor(9841.2314, grad_fn=<DivBackward0>)


In [30]:
# Training function
n=5000
for i in range(n):
    pred=model(inputs)
    loss=MSE(pred, targets)
    loss.backward()
    with torch.no_grad():
        w -=w.grad * 1e-5
        b -=b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    print(f"Epochs: {i}/{n}----Loss: {loss}")
    

Epochs: 0/5000----Loss: 333.4637756347656
Epochs: 1/5000----Loss: 333.4261474609375
Epochs: 2/5000----Loss: 333.38861083984375
Epochs: 3/5000----Loss: 333.3511047363281
Epochs: 4/5000----Loss: 333.3138122558594
Epochs: 5/5000----Loss: 333.2766418457031
Epochs: 6/5000----Loss: 333.239501953125
Epochs: 7/5000----Loss: 333.20257568359375
Epochs: 8/5000----Loss: 333.16583251953125
Epochs: 9/5000----Loss: 333.12921142578125
Epochs: 10/5000----Loss: 333.092529296875
Epochs: 11/5000----Loss: 333.0560607910156
Epochs: 12/5000----Loss: 333.01971435546875
Epochs: 13/5000----Loss: 332.9834899902344
Epochs: 14/5000----Loss: 332.9473571777344
Epochs: 15/5000----Loss: 332.9113464355469
Epochs: 16/5000----Loss: 332.87554931640625
Epochs: 17/5000----Loss: 332.8396911621094
Epochs: 18/5000----Loss: 332.8040466308594
Epochs: 19/5000----Loss: 332.7685546875
Epochs: 20/5000----Loss: 332.73309326171875
Epochs: 21/5000----Loss: 332.6977844238281
Epochs: 22/5000----Loss: 332.6626281738281
Epochs: 23/5000----

Epochs: 243/5000----Loss: 326.9841613769531
Epochs: 244/5000----Loss: 326.9655456542969
Epochs: 245/5000----Loss: 326.94696044921875
Epochs: 246/5000----Loss: 326.9283752441406
Epochs: 247/5000----Loss: 326.91009521484375
Epochs: 248/5000----Loss: 326.8916015625
Epochs: 249/5000----Loss: 326.8731994628906
Epochs: 250/5000----Loss: 326.85491943359375
Epochs: 251/5000----Loss: 326.83660888671875
Epochs: 252/5000----Loss: 326.8184509277344
Epochs: 253/5000----Loss: 326.8002014160156
Epochs: 254/5000----Loss: 326.78204345703125
Epochs: 255/5000----Loss: 326.7638854980469
Epochs: 256/5000----Loss: 326.7458801269531
Epochs: 257/5000----Loss: 326.7279357910156
Epochs: 258/5000----Loss: 326.7098693847656
Epochs: 259/5000----Loss: 326.6919250488281
Epochs: 260/5000----Loss: 326.6741943359375
Epochs: 261/5000----Loss: 326.65631103515625
Epochs: 262/5000----Loss: 326.63848876953125
Epochs: 263/5000----Loss: 326.62078857421875
Epochs: 264/5000----Loss: 326.6030578613281
Epochs: 265/5000----Loss: 3

Epochs: 510/5000----Loss: 323.31182861328125
Epochs: 511/5000----Loss: 323.3017272949219
Epochs: 512/5000----Loss: 323.2917785644531
Epochs: 513/5000----Loss: 323.28192138671875
Epochs: 514/5000----Loss: 323.27191162109375
Epochs: 515/5000----Loss: 323.26202392578125
Epochs: 516/5000----Loss: 323.2520751953125
Epochs: 517/5000----Loss: 323.2422180175781
Epochs: 518/5000----Loss: 323.23248291015625
Epochs: 519/5000----Loss: 323.22247314453125
Epochs: 520/5000----Loss: 323.2127380371094
Epochs: 521/5000----Loss: 323.20294189453125
Epochs: 522/5000----Loss: 323.19317626953125
Epochs: 523/5000----Loss: 323.1835021972656
Epochs: 524/5000----Loss: 323.1736755371094
Epochs: 525/5000----Loss: 323.1640625
Epochs: 526/5000----Loss: 323.154296875
Epochs: 527/5000----Loss: 323.1446228027344
Epochs: 528/5000----Loss: 323.13507080078125
Epochs: 529/5000----Loss: 323.1255187988281
Epochs: 530/5000----Loss: 323.1158142089844
Epochs: 531/5000----Loss: 323.10638427734375
Epochs: 532/5000----Loss: 323.09

Epochs: 782/5000----Loss: 321.23858642578125
Epochs: 783/5000----Loss: 321.2330017089844
Epochs: 784/5000----Loss: 321.2272644042969
Epochs: 785/5000----Loss: 321.22161865234375
Epochs: 786/5000----Loss: 321.21600341796875
Epochs: 787/5000----Loss: 321.2102966308594
Epochs: 788/5000----Loss: 321.20477294921875
Epochs: 789/5000----Loss: 321.1990661621094
Epochs: 790/5000----Loss: 321.1934509277344
Epochs: 791/5000----Loss: 321.18780517578125
Epochs: 792/5000----Loss: 321.1823425292969
Epochs: 793/5000----Loss: 321.1766662597656
Epochs: 794/5000----Loss: 321.1711730957031
Epochs: 795/5000----Loss: 321.16546630859375
Epochs: 796/5000----Loss: 321.1600341796875
Epochs: 797/5000----Loss: 321.15447998046875
Epochs: 798/5000----Loss: 321.1490173339844
Epochs: 799/5000----Loss: 321.14349365234375
Epochs: 800/5000----Loss: 321.137939453125
Epochs: 801/5000----Loss: 321.132568359375
Epochs: 802/5000----Loss: 321.12701416015625
Epochs: 803/5000----Loss: 321.12152099609375
Epochs: 804/5000----Loss

Epochs: 1060/5000----Loss: 320.0228271484375
Epochs: 1061/5000----Loss: 320.0195007324219
Epochs: 1062/5000----Loss: 320.0162048339844
Epochs: 1063/5000----Loss: 320.01300048828125
Epochs: 1064/5000----Loss: 320.00970458984375
Epochs: 1065/5000----Loss: 320.00640869140625
Epochs: 1066/5000----Loss: 320.0031433105469
Epochs: 1067/5000----Loss: 319.99993896484375
Epochs: 1068/5000----Loss: 319.9967041015625
Epochs: 1069/5000----Loss: 319.9934387207031
Epochs: 1070/5000----Loss: 319.99029541015625
Epochs: 1071/5000----Loss: 319.9870910644531
Epochs: 1072/5000----Loss: 319.9838562011719
Epochs: 1073/5000----Loss: 319.98065185546875
Epochs: 1074/5000----Loss: 319.9773864746094
Epochs: 1075/5000----Loss: 319.9742736816406
Epochs: 1076/5000----Loss: 319.9711608886719
Epochs: 1077/5000----Loss: 319.96783447265625
Epochs: 1078/5000----Loss: 319.9647216796875
Epochs: 1079/5000----Loss: 319.96160888671875
Epochs: 1080/5000----Loss: 319.9583435058594
Epochs: 1081/5000----Loss: 319.95526123046875
E

Epochs: 1363/5000----Loss: 319.27093505859375
Epochs: 1364/5000----Loss: 319.2690734863281
Epochs: 1365/5000----Loss: 319.2673645019531
Epochs: 1366/5000----Loss: 319.26544189453125
Epochs: 1367/5000----Loss: 319.26373291015625
Epochs: 1368/5000----Loss: 319.26190185546875
Epochs: 1369/5000----Loss: 319.2599792480469
Epochs: 1370/5000----Loss: 319.25823974609375
Epochs: 1371/5000----Loss: 319.2564697265625
Epochs: 1372/5000----Loss: 319.254638671875
Epochs: 1373/5000----Loss: 319.2529296875
Epochs: 1374/5000----Loss: 319.2510986328125
Epochs: 1375/5000----Loss: 319.2492370605469
Epochs: 1376/5000----Loss: 319.24749755859375
Epochs: 1377/5000----Loss: 319.2456970214844
Epochs: 1378/5000----Loss: 319.24383544921875
Epochs: 1379/5000----Loss: 319.24212646484375
Epochs: 1380/5000----Loss: 319.2403564453125
Epochs: 1381/5000----Loss: 319.2386474609375
Epochs: 1382/5000----Loss: 319.2369689941406
Epochs: 1383/5000----Loss: 319.235107421875
Epochs: 1384/5000----Loss: 319.2334289550781
Epochs:

Epochs: 1661/5000----Loss: 318.85711669921875
Epochs: 1662/5000----Loss: 318.8560485839844
Epochs: 1663/5000----Loss: 318.8551025390625
Epochs: 1664/5000----Loss: 318.85406494140625
Epochs: 1665/5000----Loss: 318.8530578613281
Epochs: 1666/5000----Loss: 318.85198974609375
Epochs: 1667/5000----Loss: 318.8509216308594
Epochs: 1668/5000----Loss: 318.8500061035156
Epochs: 1669/5000----Loss: 318.84906005859375
Epochs: 1670/5000----Loss: 318.8479919433594
Epochs: 1671/5000----Loss: 318.846923828125
Epochs: 1672/5000----Loss: 318.8459777832031
Epochs: 1673/5000----Loss: 318.844970703125
Epochs: 1674/5000----Loss: 318.8439025878906
Epochs: 1675/5000----Loss: 318.8429260253906
Epochs: 1676/5000----Loss: 318.8419494628906
Epochs: 1677/5000----Loss: 318.8409423828125
Epochs: 1678/5000----Loss: 318.8399963378906
Epochs: 1679/5000----Loss: 318.8389892578125
Epochs: 1680/5000----Loss: 318.83795166015625
Epochs: 1681/5000----Loss: 318.8369140625
Epochs: 1682/5000----Loss: 318.83599853515625
Epochs: 1

Epochs: 1932/5000----Loss: 318.6390686035156
Epochs: 1933/5000----Loss: 318.6384582519531
Epochs: 1934/5000----Loss: 318.63787841796875
Epochs: 1935/5000----Loss: 318.6371765136719
Epochs: 1936/5000----Loss: 318.6366271972656
Epochs: 1937/5000----Loss: 318.6360778808594
Epochs: 1938/5000----Loss: 318.63531494140625
Epochs: 1939/5000----Loss: 318.6348571777344
Epochs: 1940/5000----Loss: 318.63421630859375
Epochs: 1941/5000----Loss: 318.63360595703125
Epochs: 1942/5000----Loss: 318.6329650878906
Epochs: 1943/5000----Loss: 318.63238525390625
Epochs: 1944/5000----Loss: 318.63177490234375
Epochs: 1945/5000----Loss: 318.6311340332031
Epochs: 1946/5000----Loss: 318.630615234375
Epochs: 1947/5000----Loss: 318.63006591796875
Epochs: 1948/5000----Loss: 318.62933349609375
Epochs: 1949/5000----Loss: 318.6287841796875
Epochs: 1950/5000----Loss: 318.6281433105469
Epochs: 1951/5000----Loss: 318.6275939941406
Epochs: 1952/5000----Loss: 318.6270446777344
Epochs: 1953/5000----Loss: 318.62640380859375
Ep

Epochs: 2201/5000----Loss: 318.5086975097656
Epochs: 2202/5000----Loss: 318.5082092285156
Epochs: 2203/5000----Loss: 318.5079345703125
Epochs: 2204/5000----Loss: 318.507568359375
Epochs: 2205/5000----Loss: 318.5071716308594
Epochs: 2206/5000----Loss: 318.5068359375
Epochs: 2207/5000----Loss: 318.50653076171875
Epochs: 2208/5000----Loss: 318.50604248046875
Epochs: 2209/5000----Loss: 318.5057067871094
Epochs: 2210/5000----Loss: 318.50531005859375
Epochs: 2211/5000----Loss: 318.5050354003906
Epochs: 2212/5000----Loss: 318.50457763671875
Epochs: 2213/5000----Loss: 318.5041809082031
Epochs: 2214/5000----Loss: 318.50384521484375
Epochs: 2215/5000----Loss: 318.50341796875
Epochs: 2216/5000----Loss: 318.5030822753906
Epochs: 2217/5000----Loss: 318.502685546875
Epochs: 2218/5000----Loss: 318.5022888183594
Epochs: 2219/5000----Loss: 318.501953125
Epochs: 2220/5000----Loss: 318.5016784667969
Epochs: 2221/5000----Loss: 318.50115966796875
Epochs: 2222/5000----Loss: 318.5008850097656
Epochs: 2223/50

Epochs: 2498/5000----Loss: 318.4226379394531
Epochs: 2499/5000----Loss: 318.42236328125
Epochs: 2500/5000----Loss: 318.42230224609375
Epochs: 2501/5000----Loss: 318.4221496582031
Epochs: 2502/5000----Loss: 318.4217529296875
Epochs: 2503/5000----Loss: 318.421630859375
Epochs: 2504/5000----Loss: 318.4213562011719
Epochs: 2505/5000----Loss: 318.42108154296875
Epochs: 2506/5000----Loss: 318.4208984375
Epochs: 2507/5000----Loss: 318.420654296875
Epochs: 2508/5000----Loss: 318.4205017089844
Epochs: 2509/5000----Loss: 318.42022705078125
Epochs: 2510/5000----Loss: 318.4200134277344
Epochs: 2511/5000----Loss: 318.4197998046875
Epochs: 2512/5000----Loss: 318.4195251464844
Epochs: 2513/5000----Loss: 318.4193420410156
Epochs: 2514/5000----Loss: 318.41912841796875
Epochs: 2515/5000----Loss: 318.4189758300781
Epochs: 2516/5000----Loss: 318.4187316894531
Epochs: 2517/5000----Loss: 318.41851806640625
Epochs: 2518/5000----Loss: 318.418212890625
Epochs: 2519/5000----Loss: 318.41802978515625
Epochs: 2520

Epochs: 2794/5000----Loss: 318.3715515136719
Epochs: 2795/5000----Loss: 318.3714904785156
Epochs: 2796/5000----Loss: 318.37139892578125
Epochs: 2797/5000----Loss: 318.3711853027344
Epochs: 2798/5000----Loss: 318.3710632324219
Epochs: 2799/5000----Loss: 318.3709716796875
Epochs: 2800/5000----Loss: 318.3706970214844
Epochs: 2801/5000----Loss: 318.37066650390625
Epochs: 2802/5000----Loss: 318.37054443359375
Epochs: 2803/5000----Loss: 318.3704528808594
Epochs: 2804/5000----Loss: 318.37042236328125
Epochs: 2805/5000----Loss: 318.3702697753906
Epochs: 2806/5000----Loss: 318.3700256347656
Epochs: 2807/5000----Loss: 318.36993408203125
Epochs: 2808/5000----Loss: 318.36968994140625
Epochs: 2809/5000----Loss: 318.3697509765625
Epochs: 2810/5000----Loss: 318.36944580078125
Epochs: 2811/5000----Loss: 318.36932373046875
Epochs: 2812/5000----Loss: 318.3692932128906
Epochs: 2813/5000----Loss: 318.3691711425781
Epochs: 2814/5000----Loss: 318.3690185546875
Epochs: 2815/5000----Loss: 318.3689270019531
Ep

Epochs: 3076/5000----Loss: 318.34136962890625
Epochs: 3077/5000----Loss: 318.34124755859375
Epochs: 3078/5000----Loss: 318.3410949707031
Epochs: 3079/5000----Loss: 318.34112548828125
Epochs: 3080/5000----Loss: 318.341064453125
Epochs: 3081/5000----Loss: 318.3409118652344
Epochs: 3082/5000----Loss: 318.3408508300781
Epochs: 3083/5000----Loss: 318.34075927734375
Epochs: 3084/5000----Loss: 318.3406677246094
Epochs: 3085/5000----Loss: 318.34051513671875
Epochs: 3086/5000----Loss: 318.3404846191406
Epochs: 3087/5000----Loss: 318.3404846191406
Epochs: 3088/5000----Loss: 318.34039306640625
Epochs: 3089/5000----Loss: 318.34014892578125
Epochs: 3090/5000----Loss: 318.34002685546875
Epochs: 3091/5000----Loss: 318.33990478515625
Epochs: 3092/5000----Loss: 318.33978271484375
Epochs: 3093/5000----Loss: 318.33984375
Epochs: 3094/5000----Loss: 318.3396911621094
Epochs: 3095/5000----Loss: 318.339599609375
Epochs: 3096/5000----Loss: 318.3395690917969
Epochs: 3097/5000----Loss: 318.3394470214844
Epochs:

Epochs: 3377/5000----Loss: 318.3199768066406
Epochs: 3378/5000----Loss: 318.32000732421875
Epochs: 3379/5000----Loss: 318.31982421875
Epochs: 3380/5000----Loss: 318.3197937011719
Epochs: 3381/5000----Loss: 318.3197021484375
Epochs: 3382/5000----Loss: 318.3196716308594
Epochs: 3383/5000----Loss: 318.3196105957031
Epochs: 3384/5000----Loss: 318.3196105957031
Epochs: 3385/5000----Loss: 318.31951904296875
Epochs: 3386/5000----Loss: 318.3194885253906
Epochs: 3387/5000----Loss: 318.3194274902344
Epochs: 3388/5000----Loss: 318.3193664550781
Epochs: 3389/5000----Loss: 318.31927490234375
Epochs: 3390/5000----Loss: 318.3192138671875
Epochs: 3391/5000----Loss: 318.3191223144531
Epochs: 3392/5000----Loss: 318.3190612792969
Epochs: 3393/5000----Loss: 318.31903076171875
Epochs: 3394/5000----Loss: 318.3190002441406
Epochs: 3395/5000----Loss: 318.3189392089844
Epochs: 3396/5000----Loss: 318.3188781738281
Epochs: 3397/5000----Loss: 318.31866455078125
Epochs: 3398/5000----Loss: 318.3187561035156
Epochs:

Epochs: 3662/5000----Loss: 318.30572509765625
Epochs: 3663/5000----Loss: 318.3057861328125
Epochs: 3664/5000----Loss: 318.30572509765625
Epochs: 3665/5000----Loss: 318.3056335449219
Epochs: 3666/5000----Loss: 318.30560302734375
Epochs: 3667/5000----Loss: 318.3056640625
Epochs: 3668/5000----Loss: 318.30560302734375
Epochs: 3669/5000----Loss: 318.3055725097656
Epochs: 3670/5000----Loss: 318.3054504394531
Epochs: 3671/5000----Loss: 318.30548095703125
Epochs: 3672/5000----Loss: 318.30535888671875
Epochs: 3673/5000----Loss: 318.3053894042969
Epochs: 3674/5000----Loss: 318.30535888671875
Epochs: 3675/5000----Loss: 318.30523681640625
Epochs: 3676/5000----Loss: 318.3051452636719
Epochs: 3677/5000----Loss: 318.30523681640625
Epochs: 3678/5000----Loss: 318.3051452636719
Epochs: 3679/5000----Loss: 318.30511474609375
Epochs: 3680/5000----Loss: 318.30511474609375
Epochs: 3681/5000----Loss: 318.3050842285156
Epochs: 3682/5000----Loss: 318.3049621582031
Epochs: 3683/5000----Loss: 318.30499267578125
E

Epochs: 3956/5000----Loss: 318.29473876953125
Epochs: 3957/5000----Loss: 318.2947082519531
Epochs: 3958/5000----Loss: 318.29461669921875
Epochs: 3959/5000----Loss: 318.2945556640625
Epochs: 3960/5000----Loss: 318.2945861816406
Epochs: 3961/5000----Loss: 318.2945251464844
Epochs: 3962/5000----Loss: 318.2945251464844
Epochs: 3963/5000----Loss: 318.29437255859375
Epochs: 3964/5000----Loss: 318.29443359375
Epochs: 3965/5000----Loss: 318.2943420410156
Epochs: 3966/5000----Loss: 318.2942810058594
Epochs: 3967/5000----Loss: 318.2941589355469
Epochs: 3968/5000----Loss: 318.29412841796875
Epochs: 3969/5000----Loss: 318.2942199707031
Epochs: 3970/5000----Loss: 318.2940979003906
Epochs: 3971/5000----Loss: 318.29412841796875
Epochs: 3972/5000----Loss: 318.29412841796875
Epochs: 3973/5000----Loss: 318.29400634765625
Epochs: 3974/5000----Loss: 318.29400634765625
Epochs: 3975/5000----Loss: 318.2940368652344
Epochs: 3976/5000----Loss: 318.2939758300781
Epochs: 3977/5000----Loss: 318.29388427734375
Epo

Epochs: 4232/5000----Loss: 318.2860412597656
Epochs: 4233/5000----Loss: 318.28607177734375
Epochs: 4234/5000----Loss: 318.28594970703125
Epochs: 4235/5000----Loss: 318.28607177734375
Epochs: 4236/5000----Loss: 318.2860107421875
Epochs: 4237/5000----Loss: 318.2859191894531
Epochs: 4238/5000----Loss: 318.2859191894531
Epochs: 4239/5000----Loss: 318.28582763671875
Epochs: 4240/5000----Loss: 318.28594970703125
Epochs: 4241/5000----Loss: 318.28582763671875
Epochs: 4242/5000----Loss: 318.2858581542969
Epochs: 4243/5000----Loss: 318.28582763671875
Epochs: 4244/5000----Loss: 318.2856750488281
Epochs: 4245/5000----Loss: 318.2856140136719
Epochs: 4246/5000----Loss: 318.28558349609375
Epochs: 4247/5000----Loss: 318.28558349609375
Epochs: 4248/5000----Loss: 318.28558349609375
Epochs: 4249/5000----Loss: 318.28546142578125
Epochs: 4250/5000----Loss: 318.2854919433594
Epochs: 4251/5000----Loss: 318.28546142578125
Epochs: 4252/5000----Loss: 318.28546142578125
Epochs: 4253/5000----Loss: 318.28540039062

Epochs: 4521/5000----Loss: 318.27801513671875
Epochs: 4522/5000----Loss: 318.278076171875
Epochs: 4523/5000----Loss: 318.27801513671875
Epochs: 4524/5000----Loss: 318.27789306640625
Epochs: 4525/5000----Loss: 318.27789306640625
Epochs: 4526/5000----Loss: 318.2779846191406
Epochs: 4527/5000----Loss: 318.27789306640625
Epochs: 4528/5000----Loss: 318.27789306640625
Epochs: 4529/5000----Loss: 318.27783203125
Epochs: 4530/5000----Loss: 318.2778015136719
Epochs: 4531/5000----Loss: 318.27777099609375
Epochs: 4532/5000----Loss: 318.2777404785156
Epochs: 4533/5000----Loss: 318.27777099609375
Epochs: 4534/5000----Loss: 318.27764892578125
Epochs: 4535/5000----Loss: 318.2777099609375
Epochs: 4536/5000----Loss: 318.2775573730469
Epochs: 4537/5000----Loss: 318.2776184082031
Epochs: 4538/5000----Loss: 318.27752685546875
Epochs: 4539/5000----Loss: 318.2776184082031
Epochs: 4540/5000----Loss: 318.277587890625
Epochs: 4541/5000----Loss: 318.277587890625
Epochs: 4542/5000----Loss: 318.2774963378906
Epoch

Epochs: 4796/5000----Loss: 318.2711486816406
Epochs: 4797/5000----Loss: 318.2711181640625
Epochs: 4798/5000----Loss: 318.2710876464844
Epochs: 4799/5000----Loss: 318.27117919921875
Epochs: 4800/5000----Loss: 318.2710266113281
Epochs: 4801/5000----Loss: 318.27093505859375
Epochs: 4802/5000----Loss: 318.27099609375
Epochs: 4803/5000----Loss: 318.2708740234375
Epochs: 4804/5000----Loss: 318.2709045410156
Epochs: 4805/5000----Loss: 318.2707824707031
Epochs: 4806/5000----Loss: 318.2709045410156
Epochs: 4807/5000----Loss: 318.270751953125
Epochs: 4808/5000----Loss: 318.2706604003906
Epochs: 4809/5000----Loss: 318.2706604003906
Epochs: 4810/5000----Loss: 318.2707824707031
Epochs: 4811/5000----Loss: 318.2707824707031
Epochs: 4812/5000----Loss: 318.2706604003906
Epochs: 4813/5000----Loss: 318.2706298828125
Epochs: 4814/5000----Loss: 318.27069091796875
Epochs: 4815/5000----Loss: 318.27069091796875
Epochs: 4816/5000----Loss: 318.27056884765625
Epochs: 4817/5000----Loss: 318.27056884765625
Epochs:

In [31]:
preds=model(inputs)
preds

tensor([[ 45.9623,  80.9117],
        [ 51.2441,  49.7796],
        [ 85.7058, 125.4026],
        [ 26.9460,  30.9596],
        [107.6184, 128.4843]], grad_fn=<AddBackward0>)

In [32]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])

## Using torch built function

We've implemented linear regression & gradient descent model using some basic tensor operations. However, since this is a common pattern in deep learning, PyTorch provides several built-in functions and classes to make it easy to create and train models with just a few lines of code.

Let's begin by importing the torch.nn package from PyTorch, which contains utility classes for building neural networks.

In [33]:
import torch.nn as nn

In [34]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [35]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

We are using 15 training examples to illustrate how to work with large datasets in small batches.

## Dataset and DataLoader

We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [36]:
from torch.utils.data import TensorDataset

In [37]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [38]:
from torch.utils.data import DataLoader

In [39]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

We can use the data loader in a for loop. Let's look at an example.

In [40]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break


tensor([[ 91.,  87.,  65.],
        [ 92.,  87.,  64.],
        [ 87., 134.,  58.],
        [ 68.,  96.,  71.],
        [ 73.,  67.,  43.]])
tensor([[ 80., 102.],
        [ 82., 100.],
        [119., 133.],
        [104., 118.],
        [ 56.,  70.]])


In each iteration, the data loader returns one batch of data with the given batch size. If shuffle is set to True, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

## nn.Linear

nstead of initializing the weights & biases manually, we can define the model using the nn.Linear class from PyTorch, which does it automatically.

In [41]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[ 0.1729, -0.4657, -0.2185],
        [-0.0198,  0.4971, -0.3879]], requires_grad=True)
Parameter containing:
tensor([0.2242, 0.0150], requires_grad=True)


PyTorch models also have a helpful .parameters method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.


In [42]:
# Parameters
list(model.parameters())


[Parameter containing:
 tensor([[ 0.1729, -0.4657, -0.2185],
         [-0.0198,  0.4971, -0.3879]], requires_grad=True),
 Parameter containing:
 tensor([0.2242, 0.0150], requires_grad=True)]

In [43]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-27.7554,  15.1883],
        [-39.0127,  17.1229],
        [-59.8177,  42.3945],
        [-10.2523,   5.0109],
        [-47.8535,  19.2084],
        [-27.1168,  14.6714],
        [-38.7655,  16.2379],
        [-59.8633,  41.9868],
        [-10.8910,   5.5278],
        [-48.2449,  18.8403],
        [-27.5082,  14.3033],
        [-38.3741,  16.6060],
        [-60.0650,  43.2795],
        [ -9.8609,   5.3790],
        [-48.4921,  19.7253]], grad_fn=<AddmmBackward0>)

## Loss Function

Instead of defining a loss function manually, we can use the built-in loss function mse_loss.

In [44]:
# Import nn.functional
import torch.nn.functional as F

The nn.functional package contains many useful loss functions and several other utilities.

In [45]:
# Define loss function
loss_fn = F.mse_loss

Let's compute the loss for the current predictions of our model.

In [46]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(10630.1113, grad_fn=<MseLossBackward0>)


## Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer optim.SGD. SGD is short for "stochastic gradient descent". The term stochastic indicates that samples are selected in random batches instead of as a single group.

In [47]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Note that model.parameters() is passed as an argument to optim.SGD so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate that controls the amount by which the parameters are modified.

## Train the model

We are now ready to train the model. We'll follow the same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data instead of processing the entire training data in every iteration. Let's define a utility function fit that trains the model for a given number of epochs.

In [48]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Some things to note above:

We use the data loader defined earlier to get batches of data for every iteration.

Instead of updating parameters (weights and biases) manually, we use opt.step to perform the update and opt.zero_grad to reset the gradients to zero.

We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. loss.item returns the actual value stored in the loss tensor.

Let's train the model for 10000 epochs.

In [58]:
fit(10000, model, loss_fn, opt, train_dl)

Epoch [10/10000], Loss: 1.4477
Epoch [20/10000], Loss: 1.2127
Epoch [30/10000], Loss: 1.1874
Epoch [40/10000], Loss: 0.8488
Epoch [50/10000], Loss: 0.9678
Epoch [60/10000], Loss: 1.2249
Epoch [70/10000], Loss: 1.3920
Epoch [80/10000], Loss: 0.7308
Epoch [90/10000], Loss: 0.9319
Epoch [100/10000], Loss: 0.8753
Epoch [110/10000], Loss: 0.8323
Epoch [120/10000], Loss: 0.9652
Epoch [130/10000], Loss: 0.8570
Epoch [140/10000], Loss: 0.8403
Epoch [150/10000], Loss: 0.9978
Epoch [160/10000], Loss: 0.7324
Epoch [170/10000], Loss: 1.3965
Epoch [180/10000], Loss: 0.6629
Epoch [190/10000], Loss: 1.2298
Epoch [200/10000], Loss: 1.3910
Epoch [210/10000], Loss: 1.3921
Epoch [220/10000], Loss: 0.9864
Epoch [230/10000], Loss: 0.7814
Epoch [240/10000], Loss: 1.1643
Epoch [250/10000], Loss: 1.0725
Epoch [260/10000], Loss: 1.1879
Epoch [270/10000], Loss: 1.0514
Epoch [280/10000], Loss: 1.1657
Epoch [290/10000], Loss: 0.9420
Epoch [300/10000], Loss: 1.3197
Epoch [310/10000], Loss: 1.4642
Epoch [320/10000]

Epoch [2570/10000], Loss: 1.2194
Epoch [2580/10000], Loss: 0.9680
Epoch [2590/10000], Loss: 1.3457
Epoch [2600/10000], Loss: 1.1015
Epoch [2610/10000], Loss: 1.1123
Epoch [2620/10000], Loss: 1.4732
Epoch [2630/10000], Loss: 1.4264
Epoch [2640/10000], Loss: 1.4479
Epoch [2650/10000], Loss: 1.3902
Epoch [2660/10000], Loss: 1.0213
Epoch [2670/10000], Loss: 0.9498
Epoch [2680/10000], Loss: 1.4695
Epoch [2690/10000], Loss: 1.2870
Epoch [2700/10000], Loss: 1.0970
Epoch [2710/10000], Loss: 0.8671
Epoch [2720/10000], Loss: 0.6777
Epoch [2730/10000], Loss: 1.2343
Epoch [2740/10000], Loss: 0.7191
Epoch [2750/10000], Loss: 0.9344
Epoch [2760/10000], Loss: 1.0562
Epoch [2770/10000], Loss: 1.0088
Epoch [2780/10000], Loss: 1.2846
Epoch [2790/10000], Loss: 1.3971
Epoch [2800/10000], Loss: 1.3548
Epoch [2810/10000], Loss: 0.9284
Epoch [2820/10000], Loss: 1.0431
Epoch [2830/10000], Loss: 0.9265
Epoch [2840/10000], Loss: 0.8164
Epoch [2850/10000], Loss: 0.8040
Epoch [2860/10000], Loss: 0.9927
Epoch [287

Epoch [5090/10000], Loss: 1.1556
Epoch [5100/10000], Loss: 1.5433
Epoch [5110/10000], Loss: 0.8595
Epoch [5120/10000], Loss: 0.8722
Epoch [5130/10000], Loss: 1.4662
Epoch [5140/10000], Loss: 0.8304
Epoch [5150/10000], Loss: 0.6668
Epoch [5160/10000], Loss: 1.1592
Epoch [5170/10000], Loss: 1.2560
Epoch [5180/10000], Loss: 0.6873
Epoch [5190/10000], Loss: 0.7153
Epoch [5200/10000], Loss: 1.0455
Epoch [5210/10000], Loss: 0.7635
Epoch [5220/10000], Loss: 1.4709
Epoch [5230/10000], Loss: 0.8506
Epoch [5240/10000], Loss: 0.9669
Epoch [5250/10000], Loss: 1.2511
Epoch [5260/10000], Loss: 1.2511
Epoch [5270/10000], Loss: 1.1636
Epoch [5280/10000], Loss: 1.1975
Epoch [5290/10000], Loss: 1.1769
Epoch [5300/10000], Loss: 1.2792
Epoch [5310/10000], Loss: 1.3535
Epoch [5320/10000], Loss: 1.4859
Epoch [5330/10000], Loss: 0.9809
Epoch [5340/10000], Loss: 1.1206
Epoch [5350/10000], Loss: 0.8543
Epoch [5360/10000], Loss: 1.1693
Epoch [5370/10000], Loss: 0.8896
Epoch [5380/10000], Loss: 1.0408
Epoch [539

Epoch [7730/10000], Loss: 0.8157
Epoch [7740/10000], Loss: 0.9237
Epoch [7750/10000], Loss: 1.2386
Epoch [7760/10000], Loss: 1.2018
Epoch [7770/10000], Loss: 1.2797
Epoch [7780/10000], Loss: 0.8312
Epoch [7790/10000], Loss: 0.8726
Epoch [7800/10000], Loss: 0.7857
Epoch [7810/10000], Loss: 1.2891
Epoch [7820/10000], Loss: 0.7989
Epoch [7830/10000], Loss: 1.2304
Epoch [7840/10000], Loss: 0.9172
Epoch [7850/10000], Loss: 1.3950
Epoch [7860/10000], Loss: 0.8716
Epoch [7870/10000], Loss: 0.9098
Epoch [7880/10000], Loss: 1.4335
Epoch [7890/10000], Loss: 1.1453
Epoch [7900/10000], Loss: 1.3239
Epoch [7910/10000], Loss: 0.9807
Epoch [7920/10000], Loss: 1.4704
Epoch [7930/10000], Loss: 0.9001
Epoch [7940/10000], Loss: 1.4132
Epoch [7950/10000], Loss: 1.4726
Epoch [7960/10000], Loss: 1.5136
Epoch [7970/10000], Loss: 0.9777
Epoch [7980/10000], Loss: 0.8661
Epoch [7990/10000], Loss: 1.2105
Epoch [8000/10000], Loss: 0.8327
Epoch [8010/10000], Loss: 1.1448
Epoch [8020/10000], Loss: 0.9293
Epoch [803

In [61]:
# Generate predictions
preds = model(inputs)
preds


tensor([[ 56.9930,  70.3957],
        [ 82.0179, 100.5393],
        [118.1808, 132.7892],
        [ 20.8152,  37.7588],
        [101.8813, 118.5002],
        [ 55.7448,  69.3175],
        [ 81.8741, 100.6357],
        [118.4725, 133.3916],
        [ 22.0634,  38.8369],
        [102.9857, 119.6747],
        [ 56.8492,  70.4921],
        [ 80.7697,  99.4611],
        [118.3246, 132.6927],
        [ 19.7107,  36.5842],
        [103.1295, 119.5783]], grad_fn=<AddmmBackward0>)

In [62]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

Indeed, the predictions are quite close to our targets. We have a trained a reasonably good model to predict crop yields for apples and oranges by looking at the average temperature, rainfall, and humidity in a region. We can use it to make predictions of crop yields for new regions by passing a batch containing a single row of input.

In [63]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.5109, 67.5437]], grad_fn=<AddmmBackward0>)

The predicted yield of apples is 53.3 tons per hectare, and that of oranges is 68.3 tons per hectare.