In [1]:
import torch

In [5]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)
w=torch.tensor(1.0, requires_grad=True)
y_hat=w*x
loss=(y_hat-y)**2
print(loss)
loss.backward()
w.grad

tensor(1., grad_fn=<PowBackward0>)


tensor(-2.)

In [6]:
import numpy as np 
from copy import deepcopy
import matplotlib.pyplot as plt
x = np.array([[1,1]])
y = np.array([[0]])

In [7]:
from copy import deepcopy
import numpy as np
def feed_forward(inputs, outputs, weights):   
    print(f"Inputs: {inputs}, Outputs: {outputs}, Weights: {weights}")
    pre_hidden = np.dot(inputs,weights[0])+ weights[1]
    print(f"Pre_Hidden: {pre_hidden}")
    hidden = 1/(1+np.exp(-pre_hidden))
    print(f"Hidden : {hidden}")
    out = np.dot(hidden, weights[2]) + weights[3]
    print(f"Out : {out}")
    mean_squared_error = np.mean(np.square(out - outputs))
    print(f"MSE: {mean_squared_error}")
    return mean_squared_error

In [8]:
def update_weights(inputs, outputs, weights, lr):
    original_weights = deepcopy(weights)
    print(f"Original_weights: {original_weights}")
    temp_weights = deepcopy(weights)
    print(f"Temp_weights: {temp_weights}")
    updated_weights = deepcopy(weights)
    print(f"Updated_weights {updated_weights}")
    original_loss = feed_forward(inputs, outputs, original_weights)
    print(f"Original_loss: {original_loss}")
    for i, layer in enumerate(original_weights):
        print(f"I: {i}, Layer: {layer}")
        for index, weight in np.ndenumerate(layer):
            print(f"Index: {index}, Weight: {weight}")
            temp_weights = deepcopy(weights)
            print(f"Temp_weights: {temp_weights}")
            temp_weights[i][index] += 0.0001
            _loss_plus = feed_forward(inputs, outputs, temp_weights)
            grad = (_loss_plus - original_loss)/(0.0001)
            updated_weights[i][index] -= grad*lr
    return updated_weights, original_loss

In [9]:
W = [
    np.array([[-0.0053, 0.3793],
              [-0.5820, -0.5204],
              [-0.2723, 0.1896]], dtype=np.float32).T, 
    np.array([-0.0140, 0.5607, -0.0628], dtype=np.float32), 
    np.array([[ 0.1528, -0.1745, -0.1135]], dtype=np.float32).T, 
    np.array([-0.5516], dtype=np.float32)
]

In [10]:
W

[array([[-0.0053, -0.582 , -0.2723],
        [ 0.3793, -0.5204,  0.1896]], dtype=float32),
 array([-0.014 ,  0.5607, -0.0628], dtype=float32),
 array([[ 0.1528],
        [-0.1745],
        [-0.1135]], dtype=float32),
 array([-0.5516], dtype=float32)]

In [ ]:
losses = []
for epoch in range(100):
    W, loss = update_weights(x,y,W,0.01)
    print(f"W: {W}, loss: {loss}")
    losses.append(loss)
plt.plot(losses)
plt.title('Loss over increasing number of epochs')

Original_weights: [array([[-0.0053, -0.582 , -0.2723],
       [ 0.3793, -0.5204,  0.1896]], dtype=float32), array([-0.014 ,  0.5607, -0.0628], dtype=float32), array([[ 0.1528],
       [-0.1745],
       [-0.1135]], dtype=float32), array([-0.5516], dtype=float32)]
Temp_weights: [array([[-0.0053, -0.582 , -0.2723],
       [ 0.3793, -0.5204,  0.1896]], dtype=float32), array([-0.014 ,  0.5607, -0.0628], dtype=float32), array([[ 0.1528],
       [-0.1745],
       [-0.1135]], dtype=float32), array([-0.5516], dtype=float32)]
Updated_weights [array([[-0.0053, -0.582 , -0.2723],
       [ 0.3793, -0.5204,  0.1896]], dtype=float32), array([-0.014 ,  0.5607, -0.0628], dtype=float32), array([[ 0.1528],
       [-0.1745],
       [-0.1135]], dtype=float32), array([-0.5516], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[-0.0053, -0.582 , -0.2723],
       [ 0.3793, -0.5204,  0.1896]], dtype=float32), array([-0.014 ,  0.5607, -0.0628], dtype=float32), array([[ 0.1528],
       [-0.1745]

Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[-0.00444053, -0.5829117 , -0.27292687],
       [ 0.38015935, -0.52131164,  0.18897305]], dtype=float32), array([-0.01314053,  0.55978835, -0.06342696], dtype=float32), array([[ 0.16619825],
       [-0.1661399 ],
       [-0.10295831]], dtype=float32), array([-0.5287574], dtype=float32)]
Pre_Hidden: [[ 0.36257828 -0.54443496 -0.14738077]]
Hidden : [[0.58966442 0.3671565  0.46322136]]
Out : [[-0.53944803]]
MSE: 0.29100417816632457
W: [array([[-0.0040066 , -0.5833283 , -0.27320307],
       [ 0.38059324, -0.5217283 ,  0.1886968 ]], dtype=float32), array([-0.0127066 ,  0.5593717 , -0.06370322], dtype=float32), array([[ 0.17256106],
       [-0.162178  ],
       [-0.09795984]], dtype=float32), array([-0.51806563], dtype=float32)], loss: 0.2911120956789758
Original_weights: [array([[-0.0040066 , -0.5833283 , -0.27320307],
       [ 0.38059324, -0.5217283 ,  0.1886968 ]], dtype=float32), array([-0.0127066 ,  0.5593717 , -0.06370322], dtype=float3

 [ 0.38189724 -0.52284026  0.18799601]]
Index: (0, 0), Weight: -0.002702427562326193
Temp_weights: [array([[-0.00270243, -0.5844403 , -0.2739038 ],
       [ 0.38189724, -0.52284026,  0.18799601]], dtype=float32), array([-0.01140243,  0.5582597 , -0.064404  ], dtype=float32), array([[ 0.19039327],
       [-0.15110287],
       [-0.08397769]], dtype=float32), array([-0.48785585], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[-0.00260243, -0.5844403 , -0.2739038 ],
       [ 0.38189724, -0.52284026,  0.18799601]], dtype=float32), array([-0.01140243,  0.5582597 , -0.064404  ], dtype=float32), array([[ 0.19039327],
       [-0.15110287],
       [-0.08397769]], dtype=float32), array([-0.48785585], dtype=float32)]
Pre_Hidden: [[ 0.36789238 -0.54902083 -0.15031177]]
Hidden : [[0.59094961 0.36609161 0.46249265]]
Out : [[-0.46949958]]
MSE: 0.2204298589212315
Index: (0, 1), Weight: -0.584440290927887
Temp_weights: [array([[-0.00270243, -0.5844403 , -0.2739038 ],
       [ 0.38189

       [-0.07139343]], dtype=float32), array([-0.46064368], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[-0.00141476, -0.5853737 , -0.27444354],
       [ 0.38318473, -0.52377367,  0.18745616]], dtype=float32), array([-0.01011476,  0.55742633, -0.06494384], dtype=float32), array([[ 0.20648506],
       [-0.14114453],
       [-0.07139343]], dtype=float32), array([-0.46064368], dtype=float32)]
Pre_Hidden: [[ 0.37165521 -0.55172104 -0.15193121]]
Hidden : [[0.59185887 0.36546521 0.46209009]]
Out : [[-0.42300727]]
MSE: 0.17893515336029814
Index: (2,), Weight: -0.0649438351392746
Temp_weights: [array([[-0.00141476, -0.5853737 , -0.27444354],
       [ 0.38318473, -0.52377367,  0.18745616]], dtype=float32), array([-0.01011476,  0.5573263 , -0.06494384], dtype=float32), array([[ 0.20648506],
       [-0.14114453],
       [-0.07139343]], dtype=float32), array([-0.46064368], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[-0.00141476, -0.5853737 , -0.27444354

       [-0.06006479]], dtype=float32), array([-0.43612722], dtype=float32)]
Pre_Hidden: [[ 0.37540956 -0.55407798 -0.15316764]]
Hidden : [[0.59276547 0.3649188  0.46178278]]
Out : [[-0.38109742]]
MSE: 0.145235244145079
Index: (1, 2), Weight: 0.18704400956630707
Temp_weights: [array([[-1.6324993e-04, -5.8615935e-01, -2.7485564e-01],
       [ 3.8443607e-01, -5.2455932e-01,  1.8704401e-01]], dtype=float32), array([-0.00886326,  0.55654067, -0.065356  ], dtype=float32), array([[ 0.22100554],
       [-0.1321877 ],
       [-0.06006479]], dtype=float32), array([-0.43612722], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[-1.6324993e-04, -5.8615935e-01, -2.7485564e-01],
       [ 3.8443607e-01, -5.2455932e-01,  1.8714401e-01]], dtype=float32), array([-0.00886326,  0.55654067, -0.065356  ], dtype=float32), array([[ 0.22100554],
       [-0.1321877 ],
       [-0.06006479]], dtype=float32), array([-0.43612722], dtype=float32)]
Pre_Hidden: [[ 0.37540956 -0.554178   -0.15306763]]


Pre_Hidden: [[ 0.37901429 -0.55616713 -0.15400105]]
Hidden : [[0.59363534 0.36443478 0.46157565]]
Out : [[-0.34332]]
MSE: 0.11786862271736437
Index: (1, 0), Weight: 0.3856375515460968
Temp_weights: [array([[ 0.00103837, -0.5868224 , -0.27516675],
       [ 0.38563755, -0.52522236,  0.18673286]], dtype=float32), array([-0.00766164,  0.5558776 , -0.06566714], dtype=float32), array([[ 0.23410684],
       [-0.12412986],
       [-0.049865  ]], dtype=float32), array([-0.4140404], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00103837, -0.5868224 , -0.27516675],
       [ 0.38573754, -0.52522236,  0.18673286]], dtype=float32), array([-0.00766164,  0.5558776 , -0.06566714], dtype=float32), array([[ 0.23410684],
       [-0.12412986],
       [-0.049865  ]], dtype=float32), array([-0.4140404], dtype=float32)]
Pre_Hidden: [[ 0.37911427 -0.55616713 -0.15410104]]
Hidden : [[0.59365946 0.36443478 0.4615508 ]]
Out : [[-0.34331311]]
MSE: 0.11786389475987062
Index: (1, 1), Weight: 

Index: (2,), Weight: -0.06589864939451218
Temp_weights: [array([[ 0.00218098, -0.5873835 , -0.27539822],
       [ 0.38678002, -0.5257835 ,  0.18650134]], dtype=float32), array([-0.00651903,  0.5553165 , -0.06589865], dtype=float32), array([[ 0.24592619],
       [-0.11687963],
       [-0.0406807 ]], dtype=float32), array([-0.3941436], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00218098, -0.5873835 , -0.27539822],
       [ 0.38678002, -0.5257835 ,  0.18650134]], dtype=float32), array([-0.00651903,  0.5553165 , -0.06579865], dtype=float32), array([[ 0.24592619],
       [-0.11687963],
       [-0.0406807 ]], dtype=float32), array([-0.3941436], dtype=float32)]
Pre_Hidden: [[ 0.38244197 -0.55785048 -0.15469553]]
Hidden : [[0.59446194 0.36404496 0.46140306]]
Out : [[-0.30926949]]
MSE: 0.09564761829193248
I: 2, Layer: [[ 0.24592619]
 [-0.11687963]
 [-0.0406807 ]]
Index: (0, 0), Weight: 0.24592618644237518
Temp_weights: [array([[ 0.00218098, -0.5873835 , -0.27539822],


Out : [[-0.27851729]]
MSE: 0.07757188262256402
Index: (1, 0), Weight: -0.11035528779029846
Temp_weights: [array([[ 0.00325899, -0.5878597 , -0.27556717],
       [ 0.38785788, -0.52625966,  0.18633239]], dtype=float32), array([-0.00544102,  0.5548403 , -0.06606762], dtype=float32), array([[ 0.256587  ],
       [-0.11035529],
       [-0.03241035]], dtype=float32), array([-0.37622085], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00325899, -0.5878597 , -0.27556717],
       [ 0.38785788, -0.52625966,  0.18633239]], dtype=float32), array([-0.00544102,  0.5548403 , -0.06606762], dtype=float32), array([[ 0.256587  ],
       [-0.11025529],
       [-0.03241035]], dtype=float32), array([-0.37622085], dtype=float32)]
Pre_Hidden: [[ 0.38567586 -0.55927902 -0.15530241]]
Hidden : [[0.59524132 0.3637143  0.46125225]]
Out : [[-0.27854044]]
MSE: 0.07758477529166588
Index: (2, 0), Weight: -0.03241034597158432
Temp_weights: [array([[ 0.00325899, -0.5878597 , -0.27556717],
       

       [-0.02264886]], dtype=float32), array([-0.3550608], dtype=float32)]
Updated_weights [array([[ 0.00459119, -0.5883862 , -0.27571836],
       [ 0.3891899 , -0.52678615,  0.18618116]], dtype=float32), array([-0.00410883,  0.55431384, -0.06621885], dtype=float32), array([[ 0.26919088],
       [-0.10265994],
       [-0.02264886]], dtype=float32), array([-0.3550608], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00459119, -0.5883862 , -0.27571836],
       [ 0.3891899 , -0.52678615,  0.18618116]], dtype=float32), array([-0.00410883,  0.55431384, -0.06621885], dtype=float32), array([[ 0.26919088],
       [-0.10265994],
       [-0.02264886]], dtype=float32), array([-0.3550608], dtype=float32)]
Pre_Hidden: [[ 0.38967226 -0.56085849 -0.15575606]]
Hidden : [[0.5962038  0.36334885 0.46113952]]
Out : [[-0.24231382]]
MSE: 0.05871598599232297
Original_loss: 0.05871598599232297
I: 0, Layer: [[ 0.00459119 -0.5883862  -0.27571836]
 [ 0.3891899  -0.52678615  0.18618116]]
Ind

Pre_Hidden: [[ 0.3925307  -0.56184268 -0.15597062]]
Hidden : [[0.59689177 0.36312121 0.4610862 ]]
Out : [[-0.21822488]]
MSE: 0.04762209711009097
Index: (1,), Weight: 0.5539857745170593
Temp_weights: [array([[ 0.00551071, -0.58871424, -0.2757899 ],
       [ 0.3901093 , -0.5271142 ,  0.18610965]], dtype=float32), array([-0.00318931,  0.5539858 , -0.06629038], dtype=float32), array([[ 0.2775661 ],
       [-0.09755771],
       [-0.01617259]], dtype=float32), array([-0.34101957], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00551071, -0.58871424, -0.2757899 ],
       [ 0.3901093 , -0.5271142 ,  0.18610965]], dtype=float32), array([-0.00318931,  0.5540858 , -0.06629038], dtype=float32), array([[ 0.2775661 ],
       [-0.09755771],
       [-0.01617259]], dtype=float32), array([-0.34101957], dtype=float32)]
Pre_Hidden: [[ 0.3924307  -0.56174266 -0.15597062]]
Hidden : [[0.5968677  0.36314434 0.4610862 ]]
Out : [[-0.21823381]]
MSE: 0.04762599695920987
Index: (2,), Weight:

Temp_weights: [array([[ 0.00663255, -0.58907974, -0.27584472],
       [ 0.391231  , -0.5274797 ,  0.18605483]], dtype=float32), array([-0.00206746,  0.5536203 , -0.06634521], dtype=float32), array([[ 0.28746468],
       [-0.09153904],
       [-0.00852874]], dtype=float32), array([-0.32444537], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00663255, -0.58907974, -0.27584472],
       [ 0.391231  , -0.5274797 ,  0.18615483]], dtype=float32), array([-0.00206746,  0.5536203 , -0.06634521], dtype=float32), array([[ 0.28746468],
       [-0.09153904],
       [-0.00852874]], dtype=float32), array([-0.32444537], dtype=float32)]
Pre_Hidden: [[ 0.3957961  -0.56293917 -0.1560351 ]]
Hidden : [[0.59767721 0.36286767 0.46107018]]
Out : [[-0.18978319]]
MSE: 0.036017658072889064
I: 1, Layer: [-0.00206746  0.5536203  -0.06634521]
Index: (0,), Weight: -0.0020674567203968763
Temp_weights: [array([[ 0.00663255, -0.58907974, -0.27584472],
       [ 0.391231  , -0.5274797 ,  0.18605483]

       [-0.00345774]], dtype=float32), array([-0.31334934], dtype=float32)]
Pre_Hidden: [[ 0.39809414 -0.5636276  -0.15619118]]
Hidden : [[0.59822967 0.36270852 0.4610314 ]]
Out : [[-0.17079481]]
MSE: 0.029170867231109083
W: [array([[ 0.00764014, -0.5893784 , -0.27586636],
       [ 0.39223847, -0.5277784 ,  0.1860332 ]], dtype=float32), array([-0.00105986,  0.5533216 , -0.06636684], dtype=float32), array([[ 0.29608354],
       [-0.08630866],
       [-0.00188219]], dtype=float32), array([-0.31003287], dtype=float32)], loss: 0.02920503167868223
Original_weights: [array([[ 0.00764014, -0.5893784 , -0.27586636],
       [ 0.39223847, -0.5277784 ,  0.1860332 ]], dtype=float32), array([-0.00105986,  0.5533216 , -0.06636684], dtype=float32), array([[ 0.29608354],
       [-0.08630866],
       [-0.00188219]], dtype=float32), array([-0.31003287], dtype=float32)]
Temp_weights: [array([[ 0.00764014, -0.5893784 , -0.27586636],
       [ 0.39223847, -0.5277784 ,  0.1860332 ]], dtype=float32), array([-

       [ 0.00110833]], dtype=float32), array([-0.3035482], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00810322, -0.589507  , -0.2758682 ],
       [ 0.3927015 , -0.52790695,  0.18603137]], dtype=float32), array([-0.00059679,  0.55329305, -0.06636867], dtype=float32), array([[ 0.29996502],
       [-0.08395625],
       [ 0.00110833]], dtype=float32), array([-0.3035482], dtype=float32)]
Pre_Hidden: [[ 0.40020794 -0.56412089 -0.15620551]]
Hidden : [[0.59873762 0.3625945  0.46102784]]
Out : [[-0.15387895]]
MSE: 0.0236787299981606
Index: (2,), Weight: -0.06636866927146912
Temp_weights: [array([[ 0.00810322, -0.589507  , -0.2758682 ],
       [ 0.3927015 , -0.52790695,  0.18603137]], dtype=float32), array([-0.00059679,  0.55319303, -0.06636867], dtype=float32), array([[ 0.29996502],
       [-0.08395625],
       [ 0.00110833]], dtype=float32), array([-0.3035482], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00810322, -0.589507  , -0.2758682 ],


       [ 0.00649682]], dtype=float32), array([-0.29186392], dtype=float32)]
Pre_Hidden: [[ 0.4027567  -0.56478858 -0.15617826]]
Hidden : [[0.59934981 0.3624402  0.46103461]]
Out : [[-0.13378294]]
MSE: 0.017897875407841924
Index: (0, 2), Weight: -0.27585911750793457
Temp_weights: [array([[ 0.00895284, -0.58972955, -0.27585912],
       [ 0.39355102, -0.5281295 ,  0.18604045]], dtype=float32), array([ 2.5283822e-04,  5.5297047e-01, -6.6359587e-02], dtype=float32), array([[ 0.30696446],
       [-0.079719  ],
       [ 0.00649682]], dtype=float32), array([-0.29186392], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00895284, -0.58972955, -0.27575913],
       [ 0.39355102, -0.5281295 ,  0.18604045]], dtype=float32), array([ 2.5283822e-04,  5.5297047e-01, -6.6359587e-02], dtype=float32), array([[ 0.30696446],
       [-0.079719  ],
       [ 0.00649682]], dtype=float32), array([-0.29186392], dtype=float32)]
Pre_Hidden: [[ 0.4027567  -0.5648886  -0.15607827]]
Hidden : [[0.5

       [ 0.00892108]], dtype=float32), array([-0.28660738], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00934146, -0.58982587, -0.27584985],
       [ 0.3939396 , -0.52822584,  0.18604973]], dtype=float32), array([ 0.00064146,  0.55287415, -0.0663503 ], dtype=float32), array([[ 0.3101158 ],
       [-0.07781329],
       [ 0.00892108]], dtype=float32), array([-0.2865074], dtype=float32)]
Pre_Hidden: [[ 0.40392254 -0.56517756 -0.15615042]]
Hidden : [[0.59962973 0.36235032 0.46104152]]
Out : [[-0.12463542]]
MSE: 0.015533988103904817
W: [array([[ 0.00952719, -0.58987075, -0.2758443 ],
       [ 0.3941253 , -0.5282707 ,  0.18605526]], dtype=float32), array([ 0.00082718,  0.55282927, -0.06634478], dtype=float32), array([[ 0.31161115],
       [-0.07690945],
       [ 0.01007103]], dtype=float32), array([-0.284114], dtype=float32)], loss: 0.015558921892945698
Original_weights: [array([[ 0.00952719, -0.58987075, -0.2758443 ],
       [ 0.3941253 , -0.5282707 ,  0.18605526]]

       [ 0.01225359]], dtype=float32), array([-0.27938178], dtype=float32)]
Pre_Hidden: [[ 0.40564446 -0.56556326 -0.15609635]]
Hidden : [[0.60004304 0.36226121 0.46105496]]
Out : [[-0.11228855]]
MSE: 0.012608718421772287
Index: (0, 1), Weight: -0.5899544358253479
Temp_weights: [array([[ 0.00988213, -0.58995444, -0.27583182],
       [ 0.3944802 , -0.5283544 ,  0.18606776]], dtype=float32), array([ 0.00118213,  0.5527456 , -0.06633229], dtype=float32), array([[ 0.31445011],
       [-0.07519422],
       [ 0.01225359]], dtype=float32), array([-0.27938178], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.00988213, -0.5898544 , -0.27583182],
       [ 0.3944802 , -0.5283544 ,  0.18606776]], dtype=float32), array([ 0.00118213,  0.5527456 , -0.06633229], dtype=float32), array([[ 0.31445011],
       [-0.07519422],
       [ 0.01225359]], dtype=float32), array([-0.27938178], dtype=float32)]
Pre_Hidden: [[ 0.40554446 -0.56546324 -0.15609635]]
Hidden : [[0.60001904 0.36228432 

       [ 0.01428851]], dtype=float32), array([-0.27496985], dtype=float32)]
Pre_Hidden: [[ 0.40654586 -0.56569213 -0.15605436]]
Hidden : [[0.60025935 0.36223144 0.46106539]]
Out : [[-0.10469933]]
MSE: 0.010961950497428529
Index: (0, 2), Weight: -0.2758178412914276
Temp_weights: [array([[ 0.01021595, -0.5900307 , -0.27581784],
       [ 0.39481395, -0.5284307 ,  0.18608177]], dtype=float32), array([ 0.00151595,  0.5526693 , -0.06631829], dtype=float32), array([[ 0.3170981 ],
       [-0.07359531],
       [ 0.01428851]], dtype=float32), array([-0.27496985], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01021595, -0.5900307 , -0.27571785],
       [ 0.39481395, -0.5284307 ,  0.18608177]], dtype=float32), array([ 0.00151595,  0.5526693 , -0.06631829], dtype=float32), array([[ 0.3170981 ],
       [-0.07359531],
       [ 0.01428851]], dtype=float32), array([-0.27496985], dtype=float32)]
Pre_Hidden: [[ 0.40654586 -0.56579214 -0.15595438]]
Hidden : [[0.60025935 0.36220833 

Out : [[-0.09424194]]
MSE: 0.008881542461292354
Index: (0, 1), Weight: -0.5901328921318054
Temp_weights: [array([[ 0.01067935, -0.5901329 , -0.27579492],
       [ 0.3952773 , -0.52853286,  0.18610471]], dtype=float32), array([ 0.00197935,  0.5525671 , -0.06629533], dtype=float32), array([[ 0.3207396 ],
       [-0.07139792],
       [ 0.01708567]], dtype=float32), array([-0.26890558], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01067935, -0.5900329 , -0.27579492],
       [ 0.3952773 , -0.52853286,  0.18610471]], dtype=float32), array([ 0.00197935,  0.5525671 , -0.06629533], dtype=float32), array([[ 0.3207396 ],
       [-0.07139792],
       [ 0.01708567]], dtype=float32), array([-0.26890558], dtype=float32)]
Pre_Hidden: [[ 0.407936   -0.56599861 -0.15598554]]
Hidden : [[0.60059287 0.36216064 0.46108249]]
Out : [[-0.09425128]]
MSE: 0.008883303627000877
Index: (0, 2), Weight: -0.2757949233055115
Temp_weights: [array([[ 0.01067935, -0.5901329 , -0.27579492],
       

       [ 0.01960368]], dtype=float32), array([-0.26344687], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.011101  , -0.5902222 , -0.27577063],
       [ 0.3956989 , -0.52862215,  0.18612905]], dtype=float32), array([ 0.002501  ,  0.55247784, -0.066271  ], dtype=float32), array([[ 0.3240193 ],
       [-0.06942024],
       [ 0.01960368]], dtype=float32), array([-0.26344687], dtype=float32)]
Pre_Hidden: [[ 0.40930091 -0.56636649 -0.15591259]]
Hidden : [[0.60092024 0.36207566 0.46110062]]
Out : [[-0.08483321]]
MSE: 0.007196674228065883
Index: (1,), Weight: 0.5524778366088867
Temp_weights: [array([[ 0.011101  , -0.5902222 , -0.27577063],
       [ 0.3956989 , -0.52862215,  0.18612905]], dtype=float32), array([ 0.002401  ,  0.55247784, -0.066271  ], dtype=float32), array([[ 0.3240193 ],
       [-0.06942024],
       [ 0.01960368]], dtype=float32), array([-0.26344687], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.011101  , -0.5902222 , -0.27577063

Pre_Hidden: [[ 0.41035044 -0.5666011  -0.15583798]]
Hidden : [[0.6011719  0.36202147 0.46111916]]
Out : [[-0.07632282]]
MSE: 0.00582517336208662
I: 3, Layer: [-0.25853345]
Index: (0,), Weight: -0.25853344798088074
Temp_weights: [array([[ 0.0114842 , -0.5903004 , -0.27574578],
       [ 0.39608204, -0.52870035,  0.18615393]], dtype=float32), array([ 0.0027842 ,  0.55239964, -0.06624613], dtype=float32), array([[ 0.32697293],
       [-0.06764034],
       [ 0.02187033]], dtype=float32), array([-0.25853345], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.0114842 , -0.5903004 , -0.27574578],
       [ 0.39608204, -0.52870035,  0.18615393]], dtype=float32), array([ 0.0027842 ,  0.55239964, -0.06624613], dtype=float32), array([[ 0.32697293],
       [-0.06764034],
       [ 0.02187033]], dtype=float32), array([-0.25843346], dtype=float32)]
Pre_Hidden: [[ 0.41035044 -0.5666011  -0.15583798]]
Hidden : [[0.6011719  0.36202147 0.46111916]]
Out : [[-0.07626895]]
MSE: 0.005816952

Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.0119407 , -0.5903899 , -0.27571282],
       [ 0.39653847, -0.5287899 ,  0.1861869 ]], dtype=float32), array([ 0.0033407 ,  0.5523101 , -0.06621317], dtype=float32), array([[ 0.33045903],
       [-0.06554094],
       [ 0.0245444 ]], dtype=float32), array([-0.25273737], dtype=float32)]
Pre_Hidden: [[ 0.41181987 -0.56686968 -0.15573909]]
Hidden : [[0.60152417 0.36195944 0.46114373]]
Out : [[-0.06636295]]
MSE: 0.004404040487954999
Index: (1,), Weight: 0.5523101091384888
Temp_weights: [array([[ 0.0119407 , -0.5903899 , -0.27571282],
       [ 0.39653847, -0.5287899 ,  0.1861869 ]], dtype=float32), array([ 0.0032407 ,  0.5523101 , -0.06621317], dtype=float32), array([[ 0.33045903],
       [-0.06554094],
       [ 0.0245444 ]], dtype=float32), array([-0.25273737], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.0119407 , -0.5903899 , -0.27571282],
       [ 0.39653847, -0.5287899 ,  0.1861869 ]], dtype=float32), array([ 

       [ 0.02686836]], dtype=float32), array([-0.24770056], dtype=float32)], loss: 0.003568779046873218
Original_weights: [array([[ 0.01234133, -0.5904654 , -0.27568096],
       [ 0.39693904, -0.5288654 ,  0.18621872]], dtype=float32), array([ 0.00364133,  0.5522346 , -0.06618132], dtype=float32), array([[ 0.33349007],
       [-0.06371679],
       [ 0.02686836]], dtype=float32), array([-0.24770056], dtype=float32)]
Temp_weights: [array([[ 0.01234133, -0.5904654 , -0.27568096],
       [ 0.39693904, -0.5288654 ,  0.18621872]], dtype=float32), array([ 0.00364133,  0.5522346 , -0.06618132], dtype=float32), array([[ 0.33349007],
       [-0.06371679],
       [ 0.02686836]], dtype=float32), array([-0.24770056], dtype=float32)]
Updated_weights [array([[ 0.01234133, -0.5904654 , -0.27568096],
       [ 0.39693904, -0.5288654 ,  0.18621872]], dtype=float32), array([ 0.00364133,  0.5522346 , -0.06618132], dtype=float32), array([[ 0.33349007],
       [-0.06371679],
       [ 0.02686836]], dtype=floa

Temp_weights: [array([[ 0.01260897, -0.5905143 , -0.27565825],
       [ 0.39720666, -0.5289143 ,  0.18624148]], dtype=float32), array([ 0.00390897,  0.5521857 , -0.06615858], dtype=float32), array([[ 0.33550057],
       [-0.06250744],
       [ 0.0284093 ]], dtype=float32), array([-0.24436076], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01260897, -0.5905143 , -0.27565825],
       [ 0.39720666, -0.5289143 ,  0.18624148]], dtype=float32), array([ 0.00390897,  0.5521857 , -0.06615858], dtype=float32), array([[ 0.33560055],
       [-0.06250744],
       [ 0.0284093 ]], dtype=float32), array([-0.24436076], dtype=float32)]
Pre_Hidden: [[ 0.41372461 -0.56724286 -0.15557535]]
Hidden : [[0.60198063 0.36187326 0.46118442]]
Out : [[-0.05185357]]
MSE: 0.002688792904374777
Index: (1, 0), Weight: -0.06250744313001633
Temp_weights: [array([[ 0.01260897, -0.5905143 , -0.27565825],
       [ 0.39720666, -0.5289143 ,  0.18624148]], dtype=float32), array([ 0.00390897,  0.5521857 ,

Pre_Hidden: [[ 0.41467781 -0.56741202 -0.15548985]]
Hidden : [[0.602209   0.3618342  0.46120567]]
Out : [[-0.04511195]]
MSE: 0.00203508829733315
Original_loss: 0.00203508829733315
I: 0, Layer: [[ 0.01292673 -0.5905707  -0.27562976]
 [ 0.39752436 -0.52897066  0.18626998]]
Index: (0, 0), Weight: 0.012926728464663029
Temp_weights: [array([[ 0.01292673, -0.5905707 , -0.27562976],
       [ 0.39752436, -0.52897066,  0.18626998]], dtype=float32), array([ 0.00422673,  0.5521293 , -0.06613007], dtype=float32), array([[ 0.33787277],
       [-0.0610811 ],
       [ 0.03022697]], dtype=float32), array([-0.2404216], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01302673, -0.5905707 , -0.27562976],
       [ 0.39752436, -0.52897066,  0.18626998]], dtype=float32), array([ 0.00422673,  0.5521293 , -0.06613007], dtype=float32), array([[ 0.33787277],
       [-0.0610811 ],
       [ 0.03022697]], dtype=float32), array([-0.2404216], dtype=float32)]
Pre_Hidden: [[ 0.41477781 -0.5674120

       [ 0.03143211]], dtype=float32), array([-0.23771015], dtype=float32)]
Pre_Hidden: [[ 0.41531351 -0.56752217 -0.15543015]]
Hidden : [[0.60236127 0.36180877 0.4612205 ]]
Out : [[-0.04050144]]
MSE: 0.0016403668809499544
W: [array([[ 0.01320465, -0.59061867, -0.2756035 ],
       [ 0.39780226, -0.52901864,  0.18629622]], dtype=float32), array([ 0.00450465,  0.55208135, -0.06610383], dtype=float32), array([[ 0.3399347 ],
       [-0.05984185],
       [ 0.03180643]], dtype=float32), array([-0.23699911], dtype=float32)], loss: 0.0016484773069977187
Original_weights: [array([[ 0.01320465, -0.59061867, -0.2756035 ],
       [ 0.39780226, -0.52901864,  0.18629622]], dtype=float32), array([ 0.00450465,  0.55208135, -0.06610383], dtype=float32), array([[ 0.3399347 ],
       [-0.05984185],
       [ 0.03180643]], dtype=float32), array([-0.23699911], dtype=float32)]
Temp_weights: [array([[ 0.01320465, -0.59061867, -0.2756035 ],
       [ 0.39780226, -0.52901864,  0.18629622]], dtype=float32), array

Temp_weights: [array([[ 0.01333018, -0.59063995, -0.27559125],
       [ 0.39792776, -0.5290399 ,  0.18630847]], dtype=float32), array([ 0.00463018,  0.55206007, -0.06609158], dtype=float32), array([[ 0.34086218],
       [-0.05928459],
       [ 0.03251675]], dtype=float32), array([-0.23546012], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01343018, -0.59063995, -0.27559125],
       [ 0.39792776, -0.5290399 ,  0.18630847]], dtype=float32), array([ 0.00463018,  0.55206007, -0.06609158], dtype=float32), array([[ 0.34086218],
       [-0.05928459],
       [ 0.03251675]], dtype=float32), array([-0.23546012], dtype=float32)]
Pre_Hidden: [[ 0.41598812 -0.5676198  -0.15537436]]
Hidden : [[0.60252284 0.36178622 0.46123437]]
Out : [[-0.03653337]]
MSE: 0.0013346870846793215
Index: (0, 1), Weight: -0.5906399488449097
Temp_weights: [array([[ 0.01333018, -0.59063995, -0.27559125],
       [ 0.39792776, -0.5290399 ,  0.18630847]], dtype=float32), array([ 0.00463018,  0.55206007,

Out : [[-0.0328887]]
MSE: 0.0010816665359388458
Index: (2,), Weight: -0.06607429683208466
Temp_weights: [array([[ 0.01350324, -0.5906688 , -0.275574  ],
       [ 0.3981008 , -0.52906877,  0.18632576]], dtype=float32), array([ 0.00480324,  0.5520312 , -0.0660743 ], dtype=float32), array([[ 0.34213695],
       [-0.05851883],
       [ 0.0334929 ]], dtype=float32), array([-0.23334539], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01350324, -0.5906688 , -0.275574  ],
       [ 0.3981008 , -0.52906877,  0.18632576]], dtype=float32), array([ 0.00480324,  0.5520312 , -0.0659743 ], dtype=float32), array([[ 0.34213695],
       [-0.05851883],
       [ 0.0334929 ]], dtype=float32), array([-0.23334539], dtype=float32)]
Pre_Hidden: [[ 0.41640728 -0.56770635 -0.15522254]]
Hidden : [[0.60262322 0.36176624 0.46127209]]
Out : [[-0.03288652]]
MSE: 0.0010815229024516782
I: 2, Layer: [[ 0.34213695]
 [-0.05851883]
 [ 0.0334929 ]]
Index: (0, 0), Weight: 0.342136949300766
Temp_weights:

Hidden : [[0.60277045 0.361743   0.46126295]]
Out : [[-0.02857697]]
MSE: 0.0008166431697902797
Original_loss: 0.0008166431697902797
I: 0, Layer: [[ 0.01370819 -0.59070235 -0.27555293]
 [ 0.3983057  -0.5291023   0.18634681]]
Index: (0, 0), Weight: 0.013708194717764854
Temp_weights: [array([[ 0.01370819, -0.59070235, -0.27555293],
       [ 0.3983057 , -0.5291023 ,  0.18634681]], dtype=float32), array([ 0.00500819,  0.55199766, -0.06605323], dtype=float32), array([[ 0.3436407 ],
       [-0.0576157 ],
       [ 0.03464422]], dtype=float32), array([-0.23085146], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01380819, -0.59070235, -0.27555293],
       [ 0.3983057 , -0.5291023 ,  0.18634681]], dtype=float32), array([ 0.00500819,  0.55199766, -0.06605323], dtype=float32), array([[ 0.3436407 ],
       [-0.0576157 ],
       [ 0.03464422]], dtype=float32), array([-0.23085146], dtype=float32)]
Pre_Hidden: [[ 0.4171221  -0.56780702 -0.15525935]]
Hidden : [[0.60279439 0.361743

Temp_weights: [array([[ 0.01384457, -0.59072435, -0.27553856],
       [ 0.3984421 , -0.5291243 ,  0.18636116]], dtype=float32), array([ 0.00514457,  0.55197567, -0.06603888], dtype=float32), array([[ 0.3446378 ],
       [-0.057017  ],
       [ 0.03540751]], dtype=float32), array([-0.2291983], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01384457, -0.59072435, -0.27553856],
       [ 0.3984421 , -0.5291243 ,  0.18646117]], dtype=float32), array([ 0.00514457,  0.55197567, -0.06603888], dtype=float32), array([[ 0.3446378 ],
       [-0.057017  ],
       [ 0.03540751]], dtype=float32), array([-0.2291983], dtype=float32)]
Pre_Hidden: [[ 0.41743122 -0.567873   -0.15511627]]
Hidden : [[0.6028684  0.36172776 0.4612985 ]]
Out : [[-0.02571826]]
MSE: 0.0006614288511793855
I: 1, Layer: [ 0.00514457  0.55197567 -0.06603888]
Index: (0,), Weight: 0.0051445672288537025
Temp_weights: [array([[ 0.01384457, -0.59072435, -0.27553856],
       [ 0.3984421 , -0.5291243 ,  0.18636116]],

Pre_Hidden: [[ 0.41801528 -0.56794971 -0.15516423]]
Hidden : [[0.60300823 0.36171005 0.46128658]]
Out : [[-0.02234009]]
MSE: 0.0004990797780113365
Index: (0, 1), Weight: -0.5907499194145203
Temp_weights: [array([[ 0.01400592, -0.5907499 , -0.27552122],
       [ 0.39860344, -0.5291499 ,  0.18637852]], dtype=float32), array([ 0.00530592,  0.5519501 , -0.06602153], dtype=float32), array([[ 0.34581396],
       [-0.05631091],
       [ 0.03630776]], dtype=float32), array([-0.22724882], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01400592, -0.5906499 , -0.27552122],
       [ 0.39860344, -0.5291499 ,  0.18637852]], dtype=float32), array([ 0.00530592,  0.5519501 , -0.06602153], dtype=float32), array([[ 0.34581396],
       [-0.05631091],
       [ 0.03630776]], dtype=float32), array([-0.22724882], dtype=float32)]
Pre_Hidden: [[ 0.41791528 -0.5678497  -0.15516423]]
Hidden : [[0.60298429 0.36173314 0.46128658]]
Out : [[-0.02234967]]
MSE: 0.000499507852534948
Index: (0, 2),

MSE: 0.00040452427936713177
Index: (1, 0), Weight: 0.398710697889328
Temp_weights: [array([[ 0.0141132 , -0.5907667 , -0.27550948],
       [ 0.3987107 , -0.5291667 ,  0.18639028]], dtype=float32), array([ 0.0054132 ,  0.5519333 , -0.06600978], dtype=float32), array([[ 0.34659374],
       [-0.05584282],
       [ 0.03690458]], dtype=float32), array([-0.22595663], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.0141132 , -0.5907667 , -0.27550948],
       [ 0.39881068, -0.5291667 ,  0.18639028]], dtype=float32), array([ 0.0054132 ,  0.5519333 , -0.06600978], dtype=float32), array([[ 0.34659374],
       [-0.05584282],
       [ 0.03690458]], dtype=float32), array([-0.22595663], dtype=float32)]
Pre_Hidden: [[ 0.41833708 -0.56800014 -0.15512898]]
Hidden : [[0.60308526 0.36169841 0.46129534]]
Out : [[-0.02010541]]
MSE: 0.00040422752719327466
Index: (1, 1), Weight: -0.5291666984558105
Temp_weights: [array([[ 0.0141132 , -0.5907667 , -0.27550948],
       [ 0.3987107 , -0.529

Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01420995, -0.59078175, -0.27549872],
       [ 0.39880747, -0.5291817 ,  0.18640102]], dtype=float32), array([ 0.00550995,  0.55191827, -0.06599905], dtype=float32), array([[ 0.34729552],
       [-0.0554216 ],
       [ 0.03754167]], dtype=float32), array([-0.22479394], dtype=float32)]
Pre_Hidden: [[ 0.41852737 -0.5680452  -0.15509674]]
Hidden : [[0.60313081 0.36168801 0.46130335]]
Out : [[-0.01805654]]
MSE: 0.00032603866545150397
I: 3, Layer: [-0.22479394]
Index: (0,), Weight: -0.224793940782547
Temp_weights: [array([[ 0.01420995, -0.59078175, -0.27549872],
       [ 0.39880747, -0.5291817 ,  0.18640102]], dtype=float32), array([ 0.00550995,  0.55191827, -0.06599905], dtype=float32), array([[ 0.34729552],
       [-0.0554216 ],
       [ 0.03744167]], dtype=float32), array([-0.22479394], dtype=float32)]
Inputs: [[1 1]], Outputs: [[0]], Weights: [array([[ 0.01420995, -0.59078175, -0.27549872],
       [ 0.39880747, -0.5291817 ,  0.1864010