In [1]:
import torch

In [2]:
x=torch.rand(3)
print(x)

tensor([0.9541, 0.2327, 0.0930])


In [3]:
x=torch.rand(3, requires_grad=True)
print(x)

tensor([0.8730, 0.3356, 0.5439], requires_grad=True)


In [4]:
y=x+2
print(y)

tensor([2.8730, 2.3356, 2.5439], grad_fn=<AddBackward0>)


In [5]:
z=y*y*2
print(z)

tensor([16.5088, 10.9096, 12.9428], grad_fn=<MulBackward0>)


In [6]:
z=z.mean()
print(z)

tensor(13.4537, grad_fn=<MeanBackward0>)


In [7]:
z.backward()

In [8]:
print(x.grad)

tensor([3.8307, 3.1141, 3.3919])


In [9]:
x1=torch.rand(3, requires_grad=False)
print(x1)

tensor([0.5798, 0.6543, 0.2632])


In [10]:
y1=x1+2
print(y1)

tensor([2.5798, 2.6543, 2.2632])


In [11]:
z1=y1*y1*2
print(z1)

tensor([13.3106, 14.0902, 10.2438])


In [13]:
z1.backward()#error requres grad_fn

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [23]:
x2=torch.rand(3,requires_grad=True)
print(x2)

tensor([0.2733, 0.9185, 0.5974], requires_grad=True)


In [15]:
y2=x2+2
print(y2)

tensor([2.8323, 2.1125, 2.1077], grad_fn=<AddBackward0>)


In [16]:
z2=y2*y2*2
print(z2)

tensor([16.0436,  8.9255,  8.8845], grad_fn=<MulBackward0>)


In [17]:
z2.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [18]:
v=torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z2.backward(v)
print(x2.grad)

tensor([1.1329e+00, 8.4501e+00, 8.4307e-03])


In [22]:
x2

tensor([0.8323, 0.1125, 0.1077])

In [20]:
x2.requires_grad_(False)
print(x2)

tensor([0.8323, 0.1125, 0.1077])


In [24]:
x2

tensor([0.2733, 0.9185, 0.5974], requires_grad=True)

In [25]:
y2=x2.detach()
print(y2)

tensor([0.2733, 0.9185, 0.5974])


In [26]:
x2

tensor([0.2733, 0.9185, 0.5974], requires_grad=True)

In [27]:
with torch.no_grad():
    y=x2+2
    print(y)

tensor([2.2733, 2.9185, 2.5974])


In [31]:
weights=torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
