## Roadmap 1 - Pytorch Main Module
1.1.  torch.is_tensor   - returns true if object is a tensor

1.2.  torch.tensor      - Constructs a tensor with data

1.3.  torch.from_numpy  - From numpy array to Tensor 


2.1.  torch.zeros       - Returns a tensor filled with the scalar value 0

2.2.  torch.ones        - Returns a tensor filled with the scalar value 1

2.3.  torch.empty       - Returns an empty tensor.

3.1.  torch.arange      - Returns a 1-D tensor of size ⌊end−start]/[step⌋ with values from the interval

3.2.  torch.linspace    - Returns a one-dimensional tensor of steps equally spaced points between start and end

3.3.  torch.logspace    - Returns a one-dimensional tensor of steps points logarithmically spaced 

4.1.  torch.eye         - Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

4.2.  torch.full        - Returns a tensor of size size filled with fill_value

5.1.  torch.cat         - Concatenates the given sequence of seq tensors in the given dimension.

5.2.  torch.masked_select - Returns a new 1-D tensor which indexes the input tensor according to 
                            the binary mask mask which is a ByteTensor.
5.3.  torch.nonzero     - Returns a tensor containing the indices of all non-zero elements of input. 

5.4.  torch.where       - Return a tensor of elements selected from either x or y, depending on condition

6.1.  torch.reshape     - Returns a reshaped tensor

6.2.  torch.squeeze     - Returns a tensor with all the dimensions of input of size 1 removed.

6.3.  torch.take        - Returns a new tensor with the elements of input at the given indices.

6.4.  torch.t           - Expects input to be a matrix (2-D tensor) and transposes dimensions 0 and 1.

6.5.  torch.transpose   - Returns a tensor that is a transposed version of input.

6.6.  torch.unsqueeze   - Returns a new tensor with a dimension of size one inserted at the specified position.

7.1.  torch.normal      - Returns a tensor of random numbers drawn from separate normal distributions 

7.2.  torch.rand        - Returns a tensor filled with random numbers from a uniform distribution on the
                            interval [0,1)
                            
7.3.  torch.randint     - Returns a tensor filled with random integers generated uniformly between low 
                          (inclusive) and high (exclusive).
                          
7.4.  torch.randn       - Returns a tensor filled with random numbers from a normal distribution with mean 0 
                          and variance 1 (also called the standard normal distribution).

8.1.  torch.save        - Saves an object to a disk file.

8.2.  tensor.load       - Loads an object saved with torch.save() from a file.

8.3.  torch.no_grad()   - Disable grad

8.4.  torch.enable_grad()  - Enable grad

8.5.  torch.is_nan      - Check if any nan value are there in tensor

8.6.  torch.device()    - Switch between cpu, gpu

8.7.  torch.autograd.profiler.profile - Context manager that manages autograd profiler state and holds a summary of results.

In [2]:
import os
import sys
import torch
import numpy as np

In [3]:
# Checking tensor
'''
 torch.is_tensor - returns true if object is a tensor
'''
x=np.matrix('1 2; 3 4')
value=torch.is_tensor(x)
print(f"Is x is a tensor: {value}")

Is x is a tensor: False


In [8]:
# Torch Tensor
'''
1.2. torch.tensor - Constructs a tensor with data
        - data (array_like) – Can be a list, tuple, NumPy ndarray, scalar, and other types.
'''
# Numpy to Tensor
x=np.matrix('1 2; 3 4')
x_tensor=torch.tensor(x)
print(f"Numpy to tensor: \n type:{type(x)} \n type: {type(x_tensor)} \n")
print(f"Numpy to Matrix: \n {x} \n Numpy to Tensor: {x_tensor} \n")

Numpy to tensor: 
 type:<class 'numpy.matrix'> 
 type: <class 'torch.Tensor'> 

Numpy to Matrix: 
 [[1 2]
 [3 4]] 
 Numpy to Tensor: tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 



In [11]:
# List to Tensor
x=[1,2,2,4]
x_tensor=(torch.tensor(x))
print(f"List to tensor: \n type:{type(x)} \n type: {type(x_tensor)} \n")
print(f"Lisz to Matrix: \n {x} \n Numpy to Tensor: {x_tensor} \n")

List to tensor: 
 type:<class 'list'> 
 type: <class 'torch.Tensor'> 

Lisz to Matrix: 
 [1, 2, 2, 4] 
 Numpy to Tensor: tensor([1, 2, 2, 4]) 



In [13]:
# Scaler to Tensor
x=3.142
x_tensor=torch.tensor(x)
print(f"Scaler to Tensor: {type(x)}\n {type(x_tensor)} \n {x_tensor}")

Scaler to Tensor: <class 'float'>
 <class 'torch.Tensor'> 
 3.1419999599456787


In [14]:
# Empty list to Tensor
x=[]
x_tensor=torch.tensor(x)
print(f"Scaler to Tensor: {type(x)}\n {type(x_tensor)} \n {x_tensor}")

Scaler to Tensor: <class 'list'>
 <class 'torch.Tensor'> 
 tensor([])


In [16]:
# From numpy array to Tensor 
# From Tensor to numpy array

'''
1.3 torch.from_numpy() - Numpy to Tensor

    numpy() - Tensor to Numpy

'''


x = np.array([1, 2, 3])
print("Type of x: ", type(x))
x_t = torch.from_numpy(x)
print("Type of x_t: ", type(x_t))
x_n = x_t.numpy()
print("Type of x_n: ", type(x_n))
print(x_t)
print(x_n)

Type of x:  <class 'numpy.ndarray'>
Type of x_t:  <class 'torch.Tensor'>
Type of x_n:  <class 'numpy.ndarray'>
tensor([1, 2, 3], dtype=torch.int32)
[1 2 3]


In [18]:
# Zeros

'''
2.1. torch.zeros - Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
#rows - 2, columns - 3
x_t1=torch.zeros(2,3)
print(x_t1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [22]:
x_t2=torch.zeros(5)
print(x_t2)

tensor([0., 0., 0., 0., 0.])


In [26]:
#depth - 4, rows - 2, columns - 3
x_t2=torch.zeros(4,2,3)
print(x_t2)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [24]:
x_t2.shape

torch.Size([4, 2, 3])

In [25]:
type(x_t2)

torch.Tensor

In [27]:
#ones
'''
2.2. torch.ones - Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument 
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.ones(2,3)
print(x_t1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
x_t2=torch.ones(6)
print(x_t2)

tensor([1., 1., 1., 1., 1., 1.])


In [30]:
#Empty
'''
2.3. torch.empty - Returns a empty tensor
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.empty(2,3)
print(x_t1)

tensor([[1.7753e+28, 1.3458e-14, 2.4754e-12],
        [2.4754e-12, 2.4754e-12, 2.4754e-12]])


In [31]:
x_t1=torch.empty(2,3)
print(x_t1)

tensor([[0.0000e+00, 1.0000e+00, 2.1028e+20],
        [1.0533e+21, 2.6081e+20, 6.7408e+22]])
