## Roadmap 1 - Pytorch Main Module
1.1.  torch.is_tensor   - returns true if object is a tensor

1.2.  torch.tensor      - Constructs a tensor with data

1.3.  torch.from_numpy  - From numpy array to Tensor 


2.1.  torch.zeros       - Returns a tensor filled with the scalar value 0

2.2.  torch.ones        - Returns a tensor filled with the scalar value 1

2.3.  torch.empty       - Returns an empty tensor.

3.1.  torch.arange      - Returns a 1-D tensor of size ⌊end−start]/[step⌋ with values from the interval

3.2.  torch.linspace    - Returns a one-dimensional tensor of steps equally spaced points between start and end

3.3.  torch.logspace    - Returns a one-dimensional tensor of steps points logarithmically spaced 

4.1.  torch.eye         - Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

4.2.  torch.full        - Returns a tensor of size size filled with fill_value

5.1.  torch.cat         - Concatenates the given sequence of seq tensors in the given dimension.

5.2.  torch.masked_select - Returns a new 1-D tensor which indexes the input tensor according to 
                            the binary mask mask which is a ByteTensor.
5.3.  torch.nonzero     - Returns a tensor containing the indices of all non-zero elements of input. 

5.4.  torch.where       - Return a tensor of elements selected from either x or y, depending on condition

6.1.  torch.reshape     - Returns a reshaped tensor

6.2.  torch.squeeze     - Returns a tensor with all the dimensions of input of size 1 removed.

6.3.  torch.take        - Returns a new tensor with the elements of input at the given indices.

6.4.  torch.t           - Expects input to be a matrix (2-D tensor) and transposes dimensions 0 and 1.

6.5.  torch.transpose   - Returns a tensor that is a transposed version of input.

6.6.  torch.unsqueeze   - Returns a new tensor with a dimension of size one inserted at the specified position.

7.1.  torch.normal      - Returns a tensor of random numbers drawn from separate normal distributions 

7.2.  torch.rand        - Returns a tensor filled with random numbers from a uniform distribution on the
                            interval [0,1)
                            
7.3.  torch.randint     - Returns a tensor filled with random integers generated uniformly between low 
                          (inclusive) and high (exclusive).
                          
7.4.  torch.randn       - Returns a tensor filled with random numbers from a normal distribution with mean 0 
                          and variance 1 (also called the standard normal distribution).

8.1.  torch.save        - Saves an object to a disk file.

8.2.  tensor.load       - Loads an object saved with torch.save() from a file.

8.3.  torch.no_grad()   - Disable grad

8.4.  torch.enable_grad()  - Enable grad

8.5.  torch.is_nan      - Check if any nan value are there in tensor

8.6.  torch.device()    - Switch between cpu, gpu

8.7.  torch.autograd.profiler.profile - Context manager that manages autograd profiler state and holds a summary of results.

In [1]:
import os
import sys
import torch
import numpy as np

In [3]:
# Checking tensor
'''
 torch.is_tensor - returns true if object is a tensor
'''
x=np.matrix('1 2; 3 4')
value=torch.is_tensor(x)
print(f"Is x is a tensor: {value}")

Is x is a tensor: False


In [8]:
# Torch Tensor
'''
1.2. torch.tensor - Constructs a tensor with data
        - data (array_like) – Can be a list, tuple, NumPy ndarray, scalar, and other types.
'''
# Numpy to Tensor
x=np.matrix('1 2; 3 4')
x_tensor=torch.tensor(x)
print(f"Numpy to tensor: \n type:{type(x)} \n type: {type(x_tensor)} \n")
print(f"Numpy to Matrix: \n {x} \n Numpy to Tensor: {x_tensor} \n")

Numpy to tensor: 
 type:<class 'numpy.matrix'> 
 type: <class 'torch.Tensor'> 

Numpy to Matrix: 
 [[1 2]
 [3 4]] 
 Numpy to Tensor: tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 



In [11]:
# List to Tensor
x=[1,2,2,4]
x_tensor=(torch.tensor(x))
print(f"List to tensor: \n type:{type(x)} \n type: {type(x_tensor)} \n")
print(f"Lisz to Matrix: \n {x} \n Numpy to Tensor: {x_tensor} \n")

List to tensor: 
 type:<class 'list'> 
 type: <class 'torch.Tensor'> 

Lisz to Matrix: 
 [1, 2, 2, 4] 
 Numpy to Tensor: tensor([1, 2, 2, 4]) 



In [13]:
# Scaler to Tensor
x=3.142
x_tensor=torch.tensor(x)
print(f"Scaler to Tensor: {type(x)}\n {type(x_tensor)} \n {x_tensor}")

Scaler to Tensor: <class 'float'>
 <class 'torch.Tensor'> 
 3.1419999599456787


In [14]:
# Empty list to Tensor
x=[]
x_tensor=torch.tensor(x)
print(f"Scaler to Tensor: {type(x)}\n {type(x_tensor)} \n {x_tensor}")

Scaler to Tensor: <class 'list'>
 <class 'torch.Tensor'> 
 tensor([])


In [16]:
# From numpy array to Tensor 
# From Tensor to numpy array

'''
1.3 torch.from_numpy() - Numpy to Tensor

    numpy() - Tensor to Numpy

'''


x = np.array([1, 2, 3])
print("Type of x: ", type(x))
x_t = torch.from_numpy(x)
print("Type of x_t: ", type(x_t))
x_n = x_t.numpy()
print("Type of x_n: ", type(x_n))
print(x_t)
print(x_n)

Type of x:  <class 'numpy.ndarray'>
Type of x_t:  <class 'torch.Tensor'>
Type of x_n:  <class 'numpy.ndarray'>
tensor([1, 2, 3], dtype=torch.int32)
[1 2 3]


In [18]:
# Zeros

'''
2.1. torch.zeros - Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
#rows - 2, columns - 3
x_t1=torch.zeros(2,3)
print(x_t1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [22]:
x_t2=torch.zeros(5)
print(x_t2)

tensor([0., 0., 0., 0., 0.])


In [26]:
#depth - 4, rows - 2, columns - 3
x_t2=torch.zeros(4,2,3)
print(x_t2)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [24]:
x_t2.shape

torch.Size([4, 2, 3])

In [25]:
type(x_t2)

torch.Tensor

In [27]:
#ones
'''
2.2. torch.ones - Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument 
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.ones(2,3)
print(x_t1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
x_t2=torch.ones(6)
print(x_t2)

tensor([1., 1., 1., 1., 1., 1.])


In [30]:
#Empty
'''
2.3. torch.empty - Returns a empty tensor
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.empty(2,3)
print(x_t1)

tensor([[1.7753e+28, 1.3458e-14, 2.4754e-12],
        [2.4754e-12, 2.4754e-12, 2.4754e-12]])


In [31]:
x_t1=torch.empty(2,3)
print(x_t1)

tensor([[0.0000e+00, 1.0000e+00, 2.1028e+20],
        [1.0533e+21, 2.6081e+20, 6.7408e+22]])


In [7]:
# Squeeze

'''
6.2. torch.squeeze - Returns a tensor with all the dimensions of input of size 1 removed.
        - For example, if input is of shape: (A×1×B×C×1×D) then the out tensor will be of shape: (A×B×C×D)
        - input (Tensor) – the input tensor
        - dim (int, optional) – if given, the input will be squeezed only in this dimension
        - out (Tensor, optional) – the output tensor
'''

x_t = torch.zeros(2, 1, 2, 1, 2)
print("Initial shape - ", x_t.size())

x_t_squeezed = torch.squeeze(x_t)
print("Final shape - ", x_t_squeezed.size())
#x_t_un_squeezed = torch.unsqueeze(x_t_squeezed, dim=1)
#print("Final shape - ", x_t_un_squeezed.size())

Initial shape -  torch.Size([2, 1, 2, 1, 2])
Final shape -  torch.Size([2, 2, 2])


In [9]:
# 2D Transpose

'''
6.3. torch.t - Expects input to be a matrix (2-D tensor) and transposes dimensions 0 and 1.
        - input (Tensor) – the input tensor
'''

x_t = torch.randn(2, 3)
x_t_transposed = torch.t(x_t)

print("x_t = ", x_t)
print("x_t_transposed = ", x_t_transposed)

x_t =  tensor([[-1.0288,  0.5494,  0.6806],
        [-0.6974,  1.1752, -0.1076]])
x_t_transposed =  tensor([[-1.0288, -0.6974],
        [ 0.5494,  1.1752],
        [ 0.6806, -0.1076]])


In [11]:
# Take

'''
6.4. torch.take - Returns a new tensor with the elements of input at the given indices. 
    The input tensor is treated as if it were viewed as a 1-D tensor. 
    The result takes the same shape as the indices.
        - input (Tensor) – the input tensor
        - indices (LongTensor) – the indices into tensor
'''

src = torch.tensor([4, 3, 5, 6, 7, 8])
taken_indexes = torch.take(src, torch.tensor([0, 2, 4]))

print("Extracted element = ", taken_indexes)

Extracted element =  tensor([4, 5, 7])


In [13]:
# N-D Transpose

'''
6.5. torch.transpose - Returns a tensor that is a transposed version of input. 
    The given dimensions dim0 and dim1 are swapped.
        - input (Tensor) – the input tensor
        - dim0 (int) – the first dimension to be transposed
        - dim1 (int) – the second dimension to be transposed
'''

x = torch.randn(2, 3, 2)
print("x = ", x)
x_t = torch.transpose(x, 0, 1)

print("x_t = ", x_t)

x =  tensor([[[-1.0862,  0.8559],
         [ 1.0435,  0.4969],
         [-2.0732, -0.7871]],

        [[ 0.3724, -0.9197],
         [ 0.6516, -0.3124],
         [ 0.2159,  1.9261]]])
x_t =  tensor([[[-1.0862,  0.8559],
         [ 0.3724, -0.9197]],

        [[ 1.0435,  0.4969],
         [ 0.6516, -0.3124]],

        [[-2.0732, -0.7871],
         [ 0.2159,  1.9261]]])


In [14]:
x = torch.randn(2, 3, 2)
print("x = ", x)
x_t = torch.transpose(x, 1, 0)

print("x_t = ", x_t)

x =  tensor([[[-1.6383,  0.2033],
         [ 0.1697,  1.0138],
         [-0.1441,  2.0292]],

        [[-0.8441, -0.2996],
         [ 0.2255, -0.2254],
         [ 0.4887, -0.5266]]])
x_t =  tensor([[[-1.6383,  0.2033],
         [-0.8441, -0.2996]],

        [[ 0.1697,  1.0138],
         [ 0.2255, -0.2254]],

        [[-0.1441,  2.0292],
         [ 0.4887, -0.5266]]])


In [18]:
# Unsqueeze

'''
6.6. torch.unsqueeze - Returns a new tensor with a dimension of size one inserted at the specified position.
        - input (Tensor) – the input tensor
        - dim (int) – the index at which to insert the singleton dimension
        - out (Tensor, optional) – the output tensor
'''

x_t = torch.tensor([1, 2, 3, 4])
x_t_unsqueezed = torch.unsqueeze(x_t, 0)

print("Initial size: ", x_t.size())
print("Final size: ", x_t_unsqueezed.size())
print("Final size: ", x_t_unsqueezed)

Initial size:  torch.Size([4])
Final size:  torch.Size([1, 4])
Final size:  tensor([[1, 2, 3, 4]])


In [19]:
# Normal random number

'''
7.1. torch.normal - Returns a tensor of random numbers drawn from separate normal distributions 
        whose mean and standard deviation are given.
            - mean (Tensor) – the tensor of per-element means
            - std (Tensor) – the tensor of per-element standard deviations
            - out (Tensor, optional) – the output tensor

'''

normal_random_tensor = torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))
print("normal_random_tensor = ", normal_random_tensor)

normal_random_tensor =  tensor([ 0.7328,  3.1335,  2.7413,  3.6910,  4.9385,  5.8461,  6.5349,  7.6972,
         9.0977, 10.0225])


In [20]:
# Random num

'''
7.2. torch.rand - Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)
        - sizes (int...) – a sequence of integers defining the shape of the output tensor. 
            Can be a variable number of arguments or a collection like a list or tuple.
'''

x_rand = torch.rand(2, 3)
print("x_rand = ", x_rand)

x_rand =  tensor([[0.4076, 0.2187, 0.2595],
        [0.1164, 0.3665, 0.1267]])


In [21]:
# Random Integer

'''
7.3. torch.randint - Returns a tensor filled with random integers generated uniformly between low 
    (inclusive) and high (exclusive).
        - low (int, optional) – Lowest integer to be drawn from the distribution. Default: 0.
        - high (int) – One above the highest integer to be drawn from the distribution.
        - size (tuple) – a tuple defining the shape of the output tensor.
        - out (Tensor, optional) – the output tensor
        - dtype - Data type.
'''

x_randint = torch.randint(low=-10, high=10, size=(2,2))
print("x_randint = ", x_randint)

x_randint =  tensor([[ 8, -3],
        [-8, -8]])


In [22]:
# Random normal

'''
7.4. torch.randn - Returns a tensor filled with random numbers from a normal distribution with 
    mean 0 and variance 1 (also called the standard normal distribution).
        - sizes (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.
        - out (Tensor, optional) – the output tensor
        - dtype - Data type.
'''

x_randn = torch.randn(2, 3)
print("x_randn = ", x_randn)

x_randn =  tensor([[-0.4999,  0.9589,  1.6159],
        [-0.3346,  0.5209, -0.5660]])


In [23]:
# Saving a tensor

'''
8.1. torch.save - Saves an object to a disk file.
        - obj – saved object
        - f – a file-like object (has to implement write and flush) or a string containing a file name
        - pickle_module – module used for pickling metadata and objects
        - pickle_protocol – can be specified to override the default protocol

'''

x = torch.tensor([0, 1, 2, 3, 4])
torch.save(x, 'tensor.pt')

In [24]:
# Loading a saved tensor

'''
8.2. tensor.load - Loads an object saved with torch.save() from a file.
'''

x = torch.load('tensor.pt')
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([0, 1, 2, 3, 4])


In [25]:
# Adding and disabling gradient

'''
8.3. torch.no_grad()      - Disable grad
    torch.enable_grad()  - Enable grad
'''

x = torch.zeros(1, requires_grad=True)
print("x requires grad = ", x.requires_grad)

y = x*3
print("y requires grad = ", y.requires_grad)

with torch.no_grad():
    z = x * 2
print("z requires grad = ", z.requires_grad)

x requires grad =  True
y requires grad =  True
z requires grad =  False


In [26]:
# Checking if NAN value is there in tensor

'''
8.4. torch.is_nan - Returns a new tensor with boolean elements representing if each element is NaN or not.
'''

x_in = torch.tensor([1, float('nan'), 2])
x_out = torch.isnan(x_in)

print("x_in = ", x_in)
print("x_out = ", x_out)

x_in =  tensor([1., nan, 2.])
x_out =  tensor([False,  True, False])


In [27]:
# Profiling - 1

'''
8.6. torch.autograd.profiler.profile - Context manager that manages autograd profiler state and holds a summary of results.
        - enabled (bool, optional) – Setting this to False makes this context manager a no-op. Default: True.
        - use_cuda (bool, optional) – Enables timing of CUDA events as well using the cudaEvent API. 
            Adds approximately 4us of overhead to each tensor operation. 
'''

x = torch.randn((1, 1), requires_grad=True)
with torch.autograd.profiler.profile() as prof:
    y = x ** 2
    y.backward()

print(prof)

-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                              aten::pow        34.57%      19.784ms        58.99%      33.759ms      33.759ms             1  
                                      aten::result_type        24.41%      13.972ms        24.41%      13.972ms      13.972ms             1  
                                               aten::to         0.01%       3.000us         0.01%       3.000us       3.000us             1  
                                        aten::ones_like         0.03%      16.000us        13.68%       7.827ms       7.827ms             1  
      