In [1]:
import torch

In [3]:
batch_size=10

feature=25
x=torch.rand((batch_size, feature))
print(x)
    

tensor([[0.3130, 0.6631, 0.9472, 0.2849, 0.1117, 0.2161, 0.9955, 0.3455, 0.1576,
         0.1339, 0.8404, 0.2108, 0.4772, 0.4327, 0.0334, 0.1428, 0.1553, 0.4164,
         0.8640, 0.6350, 0.1821, 0.0986, 0.3241, 0.3394, 0.6253],
        [0.6726, 0.0846, 0.3272, 0.5597, 0.1700, 0.8753, 0.6525, 0.6148, 0.1629,
         0.6007, 0.3940, 0.2581, 0.6601, 0.8918, 0.6644, 0.1672, 0.7440, 0.8763,
         0.8480, 0.4572, 0.1744, 0.1569, 0.2465, 0.8593, 0.5196],
        [0.1193, 0.1982, 0.4331, 0.6041, 0.7528, 0.3247, 0.0687, 0.8280, 0.0283,
         0.9243, 0.5973, 0.3734, 0.8526, 0.1756, 0.7059, 0.3255, 0.4488, 0.9884,
         0.6771, 0.7556, 0.8217, 0.5161, 0.1469, 0.3268, 0.4070],
        [0.6277, 0.6166, 0.0148, 0.0300, 0.6418, 0.5211, 0.9611, 0.7470, 0.6140,
         0.0089, 0.6431, 0.2348, 0.3618, 0.3748, 0.1489, 0.1341, 0.2904, 0.3913,
         0.0899, 0.6130, 0.3515, 0.4404, 0.1227, 0.3074, 0.6399],
        [0.7688, 0.6735, 0.2898, 0.0212, 0.5970, 0.8094, 0.1699, 0.8553, 0.0911,
       

In [4]:
print(x[0].shape)#x[0:]

torch.Size([25])


In [5]:
print(x[:,0])

tensor([0.3130, 0.6726, 0.1193, 0.6277, 0.7688, 0.7465, 0.9083, 0.5659, 0.9497,
        0.8447])


In [6]:
print(x[:,0].shape)

torch.Size([10])


In [7]:
print(x[:,1])

tensor([0.6631, 0.0846, 0.1982, 0.6166, 0.6735, 0.7458, 0.7814, 0.2252, 0.4103,
        0.7246])


In [8]:
print(x[2,0:1])

tensor([0.1193])


In [9]:
print(x[:,0:10])

tensor([[0.3130, 0.6631, 0.9472, 0.2849, 0.1117, 0.2161, 0.9955, 0.3455, 0.1576,
         0.1339],
        [0.6726, 0.0846, 0.3272, 0.5597, 0.1700, 0.8753, 0.6525, 0.6148, 0.1629,
         0.6007],
        [0.1193, 0.1982, 0.4331, 0.6041, 0.7528, 0.3247, 0.0687, 0.8280, 0.0283,
         0.9243],
        [0.6277, 0.6166, 0.0148, 0.0300, 0.6418, 0.5211, 0.9611, 0.7470, 0.6140,
         0.0089],
        [0.7688, 0.6735, 0.2898, 0.0212, 0.5970, 0.8094, 0.1699, 0.8553, 0.0911,
         0.2256],
        [0.7465, 0.7458, 0.8377, 0.0325, 0.1832, 0.4108, 0.5047, 0.0315, 0.7841,
         0.7884],
        [0.9083, 0.7814, 0.0070, 0.5530, 0.4762, 0.2265, 0.4885, 0.9576, 0.5438,
         0.5776],
        [0.5659, 0.2252, 0.7494, 0.5698, 0.1771, 0.5195, 0.1423, 0.3063, 0.8447,
         0.9693],
        [0.9497, 0.4103, 0.5323, 0.9555, 0.5276, 0.7258, 0.3457, 0.3280, 0.9390,
         0.6018],
        [0.8447, 0.7246, 0.2994, 0.9673, 0.6975, 0.2704, 0.5221, 0.2868, 0.1650,
         0.1941]])


In [10]:
print(x[2,0:10])

tensor([0.1193, 0.1982, 0.4331, 0.6041, 0.7528, 0.3247, 0.0687, 0.8280, 0.0283,
        0.9243])


In [12]:
#Fency Indexing
x=torch.arange(10)
print(x)
indices=[2,4,8]
print(x[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 4, 8])


In [13]:
x=torch.rand((3,5))
print(x)

tensor([[0.3144, 0.7869, 0.6416, 0.3923, 0.3349],
        [0.0429, 0.6722, 0.2516, 0.9465, 0.1830],
        [0.4784, 0.5841, 0.5519, 0.9758, 0.0186]])


In [14]:
x.shape

torch.Size([3, 5])

In [20]:
rows=torch.tensor([1,0])
print(rows)
rows.shape

tensor([1, 0])


torch.Size([2])

In [16]:
cols=torch.tensor([4,0])
cols

tensor([4, 0])

In [17]:
cols.shape

torch.Size([2])

In [19]:
print(x[rows, cols].shape)

torch.Size([2])


In [21]:
print(x[rows, cols])

tensor([0.1830, 0.3144])


In [25]:
# More advance indexing
x=torch.arange(10)
print(x[(x<2 )& (x>8)])
print(x[x.remainder(2)==0])

tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


In [26]:
#useful operation
print(torch.where(x>5, x, x*2))

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [31]:
print(torch.tensor([0,0,0,1,1,2,2,2,3,3,3,4,4,5,5]).unique())

tensor([0, 1, 2, 3, 4, 5])


In [32]:
print(x.ndimension())

1


In [33]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
print(x.numel())

10


# Reshapeing a Tensor

In [35]:
x=torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
x_3x3_view=x.view(3,3)
print(x_3x3_view)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [37]:
print(x_3x3.shape)

torch.Size([3, 3])


In [ ]:
'''
view->view act on something called contiguous tensors meaning that tensor is stored contiguously in memory

'''

In [39]:
x_3x3_reshape=x.reshape(3,3)
print(x_3x3_reshape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [40]:
y=x_3x3_view.t()
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [41]:
print(y.contiguous().view(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [42]:
x1=torch.rand((2,5))
x1

tensor([[0.1395, 0.9551, 0.4220, 0.1508, 0.2999],
        [0.7077, 0.3026, 0.3368, 0.0447, 0.3703]])

In [43]:
x2=torch.rand((2,5))
x2

tensor([[0.0923, 0.2095, 0.5379, 0.6491, 0.5694],
        [0.3392, 0.4982, 0.5546, 0.0927, 0.0866]])

In [44]:
print(torch.cat((x1,x2), dim=1))

tensor([[0.1395, 0.9551, 0.4220, 0.1508, 0.2999, 0.0923, 0.2095, 0.5379, 0.6491,
         0.5694],
        [0.7077, 0.3026, 0.3368, 0.0447, 0.3703, 0.3392, 0.4982, 0.5546, 0.0927,
         0.0866]])


In [46]:
print(torch.cat((x1,x2),dim=1).shape)

torch.Size([2, 10])


In [47]:
print(torch.cat((x1,x2), dim=0))

tensor([[0.1395, 0.9551, 0.4220, 0.1508, 0.2999],
        [0.7077, 0.3026, 0.3368, 0.0447, 0.3703],
        [0.0923, 0.2095, 0.5379, 0.6491, 0.5694],
        [0.3392, 0.4982, 0.5546, 0.0927, 0.0866]])


In [49]:
print(x1.view(-1))

tensor([0.1395, 0.9551, 0.4220, 0.1508, 0.2999, 0.7077, 0.3026, 0.3368, 0.0447,
        0.3703])


In [54]:
print(x1.view(-1).shape)

torch.Size([10])


In [65]:
batch=8
x=torch.rand((batch, 2,5))
x.shape

torch.Size([8, 2, 5])

In [62]:
z=x.view(-1)
print(z)
z.shape

tensor([0.5468, 0.7992, 0.9134, 0.6781, 0.4791, 0.0241, 0.8494, 0.4952, 0.6046,
        0.3580, 0.5000, 0.5773, 0.4563, 0.7759, 0.9730, 0.8810, 0.3187, 0.8597,
        0.5173, 0.9926, 0.1589, 0.4309, 0.1502, 0.8495, 0.1436, 0.5612, 0.2163,
        0.2621, 0.2895, 0.2674, 0.8671, 0.9539, 0.3914, 0.4677, 0.8251, 0.0616,
        0.6162, 0.9152, 0.5983, 0.8516, 0.3355, 0.1869, 0.6699, 0.2766, 0.1561,
        0.4031, 0.7574, 0.1528, 0.2415, 0.3746, 0.6159, 0.6528, 0.7115, 0.5001,
        0.3807, 0.8199, 0.7980, 0.7241, 0.2858, 0.5333, 0.4770, 0.4384, 0.9397,
        0.2239, 0.4573, 0.9985, 0.0966, 0.8070, 0.8896, 0.7905, 0.1734, 0.6104,
        0.2927, 0.2471, 0.6819, 0.5448, 0.0353, 0.6096, 0.1420, 0.3717])


torch.Size([80])

In [63]:
z=x.view(batch,-1)
print(z.shape)

torch.Size([8, 10])


In [61]:
z=x.permute(0,2,1)
z.shape

torch.Size([8, 5, 2])