### Pytorch #####
1. Core use case-replace nupy to use GPU for fast computing
2. automatic differentiations which can help in calculating gradients->We cam implements ANN

In [1]:
import torch
import numpy as np

### Tensor ###
1. A kind of data structure ->multidimensional arrays or metrices 
2. With tensors we can encode all of our parameters.

In [2]:
data=[[9,10],[4,5],[12,13]]

tensor_data=torch.tensor(data)
print(tensor_data)
print(type(tensor_data))

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]])
<class 'torch.Tensor'>


In [3]:
tensor_data[0,0]

tensor(9)

In [4]:
tensor_data[0]

tensor([ 9, 10])

In [5]:
tensor_data[1]

tensor([4, 5])

In [8]:
# Create tensor with numpy
np_data=np.array([[9,10],
                 [4,5],
                 [12,13]])
tensor_data_np=torch.tensor(np_data)
print(tensor_data_np)
print(type(tensor_data_np))

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]], dtype=torch.int32)
<class 'torch.Tensor'>


In [9]:
ones_like_data=torch.ones_like(tensor_data_np)
ones_like_data

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

In [10]:
ones_like_data=torch.ones_like(np_data)
ones_like_data

TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [11]:
ones_like_data=torch.ones_like(data)
ones_like_data

TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not list

In [12]:
# first of all convert numpy as an integer.. each  value of tensor_data_np is integer and we need to convert them into float
ones_like_data_random=torch.rand_like(tensor_data_np)
ones_like_data_random

RuntimeError: "check_uniform_bounds" not implemented for 'Int'

In [13]:
ones_like_data_random=torch.rand_like(tensor_data_np, dtype=torch.float)
ones_like_data_random

tensor([[0.5362, 0.0465],
        [0.3233, 0.9867],
        [0.5792, 0.3902]])

In [14]:
shape=(4,3)
rand_tensor=torch.rand(shape)
rand_tensor

tensor([[0.7781, 0.4482, 0.2490],
        [0.0459, 0.3628, 0.5723],
        [0.1032, 0.1651, 0.2758],
        [0.3515, 0.4732, 0.6978]])

In [15]:
shape=(4,3,2)
rand_tensor=torch.rand(shape)
rand_tensor

tensor([[[0.3427, 0.8527],
         [0.2108, 0.3615],
         [0.5535, 0.9163]],

        [[0.9666, 0.1139],
         [0.8241, 0.9387],
         [0.0021, 0.5740]],

        [[0.8811, 0.3404],
         [0.1379, 0.8069],
         [0.1950, 0.6379]],

        [[0.0204, 0.9495],
         [0.7673, 0.5552],
         [0.8435, 0.3972]]])

In [16]:
rand_tensor.shape

torch.Size([4, 3, 2])

In [18]:
ones=torch.ones(shape)# can use in bias initializations
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [19]:
zeros=torch.zeros(shape)
zeros

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [20]:
# Create Constant
ones=torch.ones(shape)
ones*3

tensor([[[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]]])

In [21]:
ones.device

device(type='cpu')

In [22]:
# for checking GPU
torch.cuda.is_available()

False

In [23]:
torch.cuda.current_device()# this function can only use when you have GPU available

AssertionError: Torch not compiled with CUDA enabled

In [24]:
if torch.cuda.is_available():
    tensor=torch.to("cuda")
    print(tensor.device)

## Concat Operations

In [25]:
ones=torch.ones(2,2)
torch.cat([ones, ones], dim=1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
torch.cat([ones,ones])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [27]:
ones

tensor([[1., 1.],
        [1., 1.]])

In [28]:
torch.cat([ones, ones,ones])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [29]:
torch.cat([ones, ones,ones], dim=1)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

# Arithmetic Operations

In [31]:
y=ones@ones
y

tensor([[2., 2.],
        [2., 2.]])

In [34]:
y=ones@ones@ones.T
y

tensor([[4., 4.],
        [4., 4.]])

In [35]:
y=ones.matmul(ones.T)
y

tensor([[2., 2.],
        [2., 2.]])

In [36]:
# For element wise multiplications
y=ones*ones
y

tensor([[1., 1.],
        [1., 1.]])

In [37]:
y=ones.mul(ones)
y

tensor([[1., 1.],
        [1., 1.]])

In [39]:
fives=ones+5
fives

tensor([[6., 6.],
        [6., 6.]])

In [40]:
fives.add_(5)# inplace additions

tensor([[11., 11.],
        [11., 11.]])

In [41]:
fives

tensor([[11., 11.],
        [11., 11.]])

In [42]:
type(ones)

torch.Tensor

In [44]:
#convert Tensor to Numpy
ones_np=ones.numpy()
type(ones_np)

numpy.ndarray

In [45]:
ones_tensor=torch.from_numpy(ones_np)
type(ones_tensor)

torch.Tensor