In [1]:
import torch

In [6]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device, requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [4]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [7]:
print(my_tensor.device)

cpu


In [8]:
print(my_tensor.shape)

torch.Size([2, 3])


In [9]:
print(my_tensor.requires_grad)

True


In [10]:
x=torch.empty(size=(3,3))
print(x)

tensor([[9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39],
        [8.4490e-39, 8.7245e-39, 1.0102e-38]])


In [11]:
x=torch.zeros((3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
x=torch.rand((3,3))
print(x)

tensor([[0.9778, 0.8142, 0.3783],
        [0.0449, 0.8901, 0.0450],
        [0.4167, 0.7192, 0.6242]])


In [13]:
x=torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [15]:
x=torch.eye(4,4)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [20]:
x=torch.arange(start=0,end=5, step=1)
x=torch.linspace(start=0.1, end=1, steps=10)
x=torch.empty(size=(1,5)).normal_(mean=0,std=1)
x=torch.empty(size=(1,5)).uniform_(0,1)
x=torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
