In [1]:
import torch

In [6]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device, requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [4]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [7]:
print(my_tensor.device)

cpu


In [8]:
print(my_tensor.shape)

torch.Size([2, 3])


In [9]:
print(my_tensor.requires_grad)

True


In [10]:
x=torch.empty(size=(3,3))
print(x)

tensor([[9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39],
        [8.4490e-39, 8.7245e-39, 1.0102e-38]])


In [11]:
x=torch.zeros((3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
x=torch.rand((3,3))
print(x)

tensor([[0.9778, 0.8142, 0.3783],
        [0.0449, 0.8901, 0.0450],
        [0.4167, 0.7192, 0.6242]])


In [13]:
x=torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [15]:
x=torch.eye(4,4)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [20]:
x=torch.arange(start=0,end=5, step=1)
x=torch.linspace(start=0.1, end=1, steps=10)
x=torch.empty(size=(1,5)).normal_(mean=0,std=1)
x=torch.empty(size=(1,5)).uniform_(0,1)
x=torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [22]:
# Initialize and convert tensor to others type
tensor=torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [23]:
# Array to tensor conversion
import numpy as np
np_array=np.zeros((5,5))
print(np_array)
tensor=torch.from_numpy(np_array)
print(tensor)
np_array_back=tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
# Tensor math and comparison operations
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
#Addition
z1=torch.empty(3)
z2=torch.add(x,y)
z=x+y
#Subtraction
z=x-y
#division
z=torch.true_divide(x,y)
torch.add(x,y,out=z1)
#inplace operatons
print(x)
t=torch.zeros(3)
t=t.add_(x)
print(t)
print(x)

tensor([1, 2, 3])
tensor([1., 2., 3.])
tensor([1, 2, 3])


In [31]:
# Matrix multiplications
x1=torch.rand((2,5))
print(x1)
x2=torch.rand((5,3))
print(x2)
x3=torch.mm(x1,x2)
print(x3)
x3=x1.mm(x2)
print(x3)

tensor([[0.2868, 0.1701, 0.1874, 0.2320, 0.0990],
        [0.4800, 0.7116, 0.8263, 0.5584, 0.6468]])
tensor([[0.6133, 0.3696, 0.2258],
        [0.6030, 0.1240, 0.1792],
        [0.9102, 0.6979, 0.3321],
        [0.3704, 0.8854, 0.2467],
        [0.7867, 0.4333, 0.4719]])
tensor([[0.6128, 0.5061, 0.2614],
        [2.1913, 1.6170, 0.9533]])
tensor([[0.6128, 0.5061, 0.2614],
        [2.1913, 1.6170, 0.9533]])


In [32]:
# matrix exponentiation
matrix_exp=torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[3.3395, 4.2177, 3.9793, 3.3454, 4.1790],
        [3.2504, 3.7772, 3.4874, 2.9725, 4.1489],
        [2.8568, 2.9791, 3.0307, 2.1551, 3.0288],
        [3.5335, 4.0030, 3.6872, 3.0275, 4.3338],
        [2.8531, 3.7505, 3.0738, 3.0640, 4.2613]])


In [33]:
#element wise multiplication
z=x*y
print(z)

tensor([ 9, 16, 21])


In [34]:
z=torch.dot(x,y)
print(z)

tensor(46)


In [42]:
# Batch matrix multiplications
batch=3
n=5
m=10
p=10
tensor1=torch.rand((batch,n,m))
print(tensor1)
tensor2=torch.rand((batch, m,p))
out_bmm=torch.bmm(tensor1,tensor2)
print(out_bmm)

tensor([[[5.8459e-01, 4.1466e-01, 4.5116e-01, 4.4165e-02, 2.3433e-01,
          6.4963e-03, 4.3691e-01, 2.7247e-01, 8.8461e-01, 6.0489e-01],
         [4.4990e-01, 1.4784e-01, 9.2632e-03, 1.3098e-01, 6.1397e-01,
          8.0351e-01, 2.0840e-01, 6.8484e-01, 4.4157e-01, 9.1523e-01],
         [4.1658e-01, 2.9692e-01, 8.6775e-01, 2.7795e-01, 7.7190e-01,
          1.0839e-01, 9.3145e-01, 1.1217e-01, 4.0049e-01, 9.3947e-01],
         [2.3882e-01, 7.1248e-01, 2.2706e-01, 6.3399e-01, 4.7661e-01,
          6.3695e-02, 7.2701e-01, 8.8493e-01, 9.2875e-01, 2.9446e-01],
         [8.2638e-01, 9.1514e-01, 6.1260e-01, 7.3179e-01, 4.6958e-01,
          5.6080e-01, 2.4924e-01, 4.3426e-01, 4.0663e-01, 3.0050e-01]],

        [[5.1823e-01, 7.4258e-01, 9.0359e-01, 1.9234e-01, 8.2796e-01,
          1.5742e-02, 7.1933e-01, 8.0944e-02, 8.2552e-05, 4.3714e-02],
         [8.4298e-01, 6.9296e-01, 3.9385e-01, 4.2411e-01, 7.4275e-01,
          8.0607e-01, 6.1441e-01, 9.5940e-01, 5.3388e-01, 6.6628e-01],
         [3

In [43]:
# Example of broadcasting
x1=torch.rand((5,5))
print(x1)

tensor([[0.5630, 0.3609, 0.0277, 0.8475, 0.5753],
        [0.8471, 0.9561, 0.1877, 0.5715, 0.1358],
        [0.9487, 0.5249, 0.5668, 0.6631, 0.0690],
        [0.2798, 0.8554, 0.6405, 0.0732, 0.8645],
        [0.0634, 0.5152, 0.3319, 0.1795, 0.8085]])


In [44]:
x2=torch.rand((1,5))
print(x2)

tensor([[0.6901, 0.9877, 0.4754, 0.2888, 0.7714]])


In [45]:
z=x1-x2
print(z)

tensor([[-0.1271, -0.6268, -0.4477,  0.5587, -0.1960],
        [ 0.1570, -0.0317, -0.2877,  0.2827, -0.6355],
        [ 0.2587, -0.4629,  0.0913,  0.3743, -0.7023],
        [-0.4103, -0.1324,  0.1650, -0.2156,  0.0932],
        [-0.6267, -0.4725, -0.1435, -0.1094,  0.0372]])


In [46]:
z=x1**x2
print(z)

tensor([[0.6727, 0.3655, 0.1818, 0.9533, 0.6528],
        [0.8918, 0.9566, 0.4514, 0.8508, 0.2144],
        [0.9643, 0.5290, 0.7634, 0.8881, 0.1272],
        [0.4152, 0.8570, 0.8091, 0.4700, 0.8938],
        [0.1490, 0.5194, 0.5920, 0.6089, 0.8488]])


In [ ]:
sum_x=torch.sum(x, dim=0)