In [1]:
import os
import sys
import torch
import numpy as np

In [2]:
#Checking tensor
'''
1.1 torch.is_tensor - returns true if object is a tensor
'''
x=np.matrix('1 2; 3 4')
value=torch.is_tensor(x)
print(f"Is x is tensor: ", value)

Is x is tensor:  False


In [5]:
# Torch tensor
'''
1.2. torch.tensor - Constructs a tensor with data
        - data (array_like) – Can be a list, tuple, NumPy ndarray, scalar, and other types.
'''
# Numpy to Tensor
x=np.matrix('1 2; 3,4')
x_tensor=torch.tensor(x)
print(f"Numpy to Tensor: ", type(x), type(x_tensor), x_tensor, "\n")

Numpy to Tensor:  <class 'numpy.matrix'> <class 'torch.Tensor'> tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 



In [6]:
# list to Tensor
x=[1,2,3,4]
x_tensor=torch.tensor(x)
print(f"List to Tensor: ", type(x), type(x_tensor), x_tensor, "\n")

List to Tensor:  <class 'list'> <class 'torch.Tensor'> tensor([1, 2, 3, 4]) 



In [7]:
# scaler to Tensor
x=3.142
x_tensor=torch.tensor(x)
print(f"Scaler to tensor: ", type(x), type(x_tensor), x_tensor, "\n")

Scaler to tensor:  <class 'float'> <class 'torch.Tensor'> tensor(3.1420) 



In [8]:
#empty list to tensor
x=[]
x_tensor=torch.tensor(x)
print(f"Empty List to Tensor", type(x), type(x_tensor), x_tensor, "\n")

Empty List to Tensor <class 'list'> <class 'torch.Tensor'> tensor([]) 



In [9]:
# From numpy array to Tensor 
# From Tensor to numpy array
'''
1.3 torch.from_numpy() - Numpy to Tensor

    numpy() - Tensor to Numpy

'''
x=np.array([1,2,3])
print(f"Type of x: ", type(x), x,"\n")
x_t=torch.from_numpy(x)
print(f"Type of x_t: ",type(x_t), x_t,"\n")
x_n=x_t.numpy()
print(f"Type of x_n: ", type(x_n), x_n, "\n")


Type of x:  <class 'numpy.ndarray'> [1 2 3] 

Type of x_t:  <class 'torch.Tensor'> tensor([1, 2, 3], dtype=torch.int32) 

Type of x_n:  <class 'numpy.ndarray'> [1 2 3] 



In [10]:
# Zeros
'''
2.1. torch.zeros - Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.zeros(2,3)
print("x_t1: ",x_t1)

x_t1:  tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
x_t2=torch.zeros(5)
print(x_t2)

tensor([0., 0., 0., 0., 0.])


In [12]:
x_t2=torch.zeros(4,2,3)
print(x_t2)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [13]:
x_t2.shape

torch.Size([4, 2, 3])

In [14]:
# Ones
'''
2.2. torch.ones - Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument 
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.ones(2,3)
print(x_t1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
x_t2=torch.ones(3,2,4)
print(x_t2)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [17]:
# Empty
'''
2.3. torch.empty - Returns a empty tensor
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.empty(2,3)
x_t2=torch.empty(4,2,3)
print(x_t1)
print(x_t2)

tensor([[0.0000e+00, 2.3694e-38, 2.6608e+23],
        [5.4646e-05, 1.0257e-08, 2.6076e-09]])
tensor([[[3.2604e-12, 7.3113e+34, 2.0706e-19],
         [7.7180e+28, 6.0041e+31, 4.2964e+24]],

        [[4.8418e+30, 1.6926e+22, 5.7886e+22],
         [6.7120e+22, 1.1632e+33, 5.6003e-02]],

        [[7.0374e+22, 6.9983e+28, 1.9859e+29],
         [4.3218e+27, 4.7423e+30, 2.2856e+20]],

        [[3.2607e-12, 7.4086e+28, 7.1463e+22],
         [4.6241e+30, 1.0552e+24, 5.5757e-02]]])


In [19]:
# Arrange
'''
3.1. torch.arrange - Returns a 1-D tensor of size ⌊end−start]/[step⌋ with values from the interval 
    [start, end) taken with common difference step beginning from start.
        - start (Number) – the starting value for the set of points. Default: 0.
        - end (Number) – the ending value for the set of points
        - step (Number) – the gap between each pair of adjacent points. Default: 1.
        - dtype - Data type.
'''
x_t1=torch.arange(start=2, end=10,step=0.5)
print(x_t1)

tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000, 6.0000,
        6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])


In [27]:
# Linspace
'''
3.2. torch.linspace - Returns a one-dimensional tensor of steps equally spaced points between start and end
        - start (Number) – the starting value for the set of points. Default: 0.
        - end (Number) – the ending value for the set of points
        - step (Number) – the gap between each pair of adjacent points. Default: 1.
        - dtype - Data type.
'''
x_t1=torch.linspace(start=-10, end=10, steps=7)
print(x_t1)

tensor([-10.0000,  -6.6667,  -3.3333,   0.0000,   3.3333,   6.6667,  10.0000])


In [28]:
#Logspac

'''
3.3. torch.logspace - Returns a one-dimensional tensor of steps points logarithmically spaced 
    between 10^start and 10^end
        - start (Number) – the starting value for the set of points. Default: 0.
        - end (Number) – the ending value for the set of points
        - step (Number) – the gap between each pair of adjacent points. Default: 1.
        - dtype - Data type.
'''
x_t1 = torch.logspace(start=-10, end=10, steps=5)
print("x_t1 = ", x_t1)

x_t1 =  tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


In [31]:
# Cat
'''
5.1. torch.cat - Concatenates the given sequence of seq tensors in the given dimension. 
    All tensors must either have the same shape (except in the concatenating dimension) or be empty.
        - seq (sequence of Tensors) 
        - dim (int, optional) – the dimension over which the tensors are concatenated
        - out (Tensor, optional) – the output tensor
'''
x=np.matrix('1 2; 3 4')
x_t=torch.tensor(x)
x_t_concat=torch.cat((x_t,x_t,x_t),0)
x_t_concat_h=torch.cat((x_t,x_t,x_t), 1)
print(x_t)
print(x_t_concat)
print(x_t_concat_h)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]], dtype=torch.int32)


In [34]:
# Masked Tensor
'''
5.2. torch.masked_select - Returns a new 1-D tensor which indexes the input tensor according to 
    the binary mask mask which is a ByteTensor.
        - input (Tensor) – the input data
        - mask (ByteTensor) – the tensor containing the binary mask to index with
        - out (Tensor, optional) – the output tensor   
'''
x=torch.randn(3,4)
print("x:", x)
mask=x.ge(0.0)
print("mask:",mask)
masked_selection=torch.masked_select(x,mask)
print("masked_selection:",masked_selection)

x: tensor([[ 0.7428, -1.4344, -0.1922, -0.2772],
        [ 0.0085,  0.3702,  0.5921,  0.6029],
        [-0.2548,  0.2559, -1.0036, -0.3435]])
mask: tensor([[ True, False, False, False],
        [ True,  True,  True,  True],
        [False,  True, False, False]])
masked_selection: tensor([0.7428, 0.0085, 0.3702, 0.5921, 0.6029, 0.2559])


In [35]:
# NonZero
'''
5.3. torch.nonzero - Returns a tensor containing the indices of all non-zero elements of input. 
    Each row in the result contains the indices of a non-zero element in input
        - input (Tensor) – the input tensor
        - out (LongTensor, optional) – the output tensor containing indices
'''
x_t=torch.tensor([1,1,1,1,0,1])
x_nonzero=torch.nonzero(x_t)
print("Non_zero element: ", x_nonzero)

Non_zero element:  tensor([[0],
        [1],
        [2],
        [3],
        [5]])


In [36]:
# Condition output
'''
5.4. torch.where - Return a tensor of elements selected from either x or y, depending on condition
        - condition (ByteTensor) – When True (nonzero), yield x, otherwise yield y
        - x (Tensor) – values selected at indices where condition is True
        - y (Tensor) – values selected at indices where condition is False
'''
x=torch.randn(3,2)
print("x:",x)
y=torch.ones(3,2)
print("y:",y)
z=torch.where(x>0,x,y)
print("z: ",z)

x: tensor([[ 1.4506,  0.5916],
        [-0.9239,  1.5988],
        [ 0.4286, -1.5760]])
y: tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
z:  tensor([[1.4506, 0.5916],
        [1.0000, 1.5988],
        [0.4286, 1.0000]])


In [38]:
# Reshape
'''
6.1. torch.reshape - Returns a tensor with the same data and number of elements as input, 
                but with the specified shape.
        - input (Tensor) – the tensor to be reshaped
        - shape (tuple of python:ints) – the new shape
'''
x_t=torch.arange(6)
x_t_reshape=x_t.reshape(2,3)
x_t_reshape1=torch.reshape(x_t,(3,2))
print(x_t_reshape)
print(x_t_reshape1)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [48]:
# Squeeze
'''
6.2. torch.squeeze - Returns a tensor with all the dimensions of input of size 1 removed.
        - For example, if input is of shape: (A×1×B×C×1×D) then the out tensor will be of shape: (A×B×C×D)
        - input (Tensor) – the input tensor
        - dim (int, optional) – if given, the input will be squeezed only in this dimension
        - out (Tensor, optional) – the output tensor
'''
x_t=torch.zeros(2,1,2,1,2,1,2)
print(x_t)
print(x_t.size())
print(x_t.dim())

tensor([[[[[[[0., 0.]],

            [[0., 0.]]]],



          [[[[0., 0.]],

            [[0., 0.]]]]]],





        [[[[[[0., 0.]],

            [[0., 0.]]]],



          [[[[0., 0.]],

            [[0., 0.]]]]]]])
torch.Size([2, 1, 2, 1, 2, 1, 2])
7


In [49]:
x_t_squeeze=torch.squeeze(x_t)
print(x_t_squeeze)
print(x_t_squeeze.size())

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])
torch.Size([2, 2, 2, 2])


In [50]:
x_t_squeeze.dim()

4

In [55]:
t = torch.rand(4, 4)
print(t)
b = t.view(2, 8)
print(b)
t.storage().data_ptr() == b.storage().data_ptr()  # `t` and `b` share the same underlying data.
b[0][0] = 3.14
print(b)
#t[0][0]

tensor([[0.4476, 0.6630, 0.3407, 0.9596],
        [0.6292, 0.3771, 0.4674, 0.8271],
        [0.8039, 0.2459, 0.8249, 0.8613],
        [0.4011, 0.8085, 0.7567, 0.3491]])
tensor([[0.4476, 0.6630, 0.3407, 0.9596, 0.6292, 0.3771, 0.4674, 0.8271],
        [0.8039, 0.2459, 0.8249, 0.8613, 0.4011, 0.8085, 0.7567, 0.3491]])
tensor([[3.1400, 0.6630, 0.3407, 0.9596, 0.6292, 0.3771, 0.4674, 0.8271],
        [0.8039, 0.2459, 0.8249, 0.8613, 0.4011, 0.8085, 0.7567, 0.3491]])


In [57]:
base = torch.tensor([[0, 1],[2, 3]])
base.is_contiguous()
t = base.transpose(0, 1)  # `t` is a view of `base`. No data movement happened here.
print(t.is_contiguous())
c = t.contiguous()
print(c)

False
tensor([[0, 2],
        [1, 3]])


In [59]:
# 2D Transpose

'''
6.3. torch.t - Expects input to be a matrix (2-D tensor) and transposes dimensions 0 and 1.
        - input (Tensor) – the input tensor
'''
x_t=torch.randn(2,3)
x_t_transposed=torch.t(x_t)
print("x_t = ", x_t)
print("x_t_transposed = ", x_t_transposed)

x_t =  tensor([[-1.3513, -0.5588, -0.0745],
        [-0.2167, -0.6491,  1.0749]])
x_t_transposed =  tensor([[-1.3513, -0.2167],
        [-0.5588, -0.6491],
        [-0.0745,  1.0749]])


In [60]:
# Take

'''
6.4. torch.take - Returns a new tensor with the elements of input at the given indices. 
    The input tensor is treated as if it were viewed as a 1-D tensor. 
    The result takes the same shape as the indices.
        - input (Tensor) – the input tensor
        - indices (LongTensor)
'''
src=torch.tensor([4,3,5,6,7,8])
taken_indexes=torch.take(src, torch.tensor([0,2,5]))
print("Extracted element = ", taken_indexes)

Extracted element =  tensor([4, 5, 8])


In [61]:
src=torch.tensor([[4,3,5],[6,7,8],[9,10,11]])
torch.take(src, torch.tensor([0,5,7]))

tensor([ 4,  8, 10])

In [63]:
# N-D Transpose

'''
6.5. torch.transpose - Returns a tensor that is a transposed version of input. 
    The given dimensions dim0 and dim1 are swapped.
        - input (Tensor) – the input tensor
        - dim0 (int) – the first dimension to be transposed
        - dim1 (int) – the second dimension to be transposed
'''
x=torch.randn(2,3,2)
print(x)
x_t=torch.transpose(x,1,0)
print(x_t)

tensor([[[-1.3120, -0.5950],
         [-1.8419,  0.5208],
         [-0.3363, -1.4828]],

        [[-0.4306,  1.1761],
         [-0.4928, -0.7707],
         [ 1.0894, -0.0870]]])
tensor([[[-1.3120, -0.5950],
         [-0.4306,  1.1761]],

        [[-1.8419,  0.5208],
         [-0.4928, -0.7707]],

        [[-0.3363, -1.4828],
         [ 1.0894, -0.0870]]])


In [64]:
x_t=torch.transpose(x,0,1)
print(x_t)

tensor([[[-1.3120, -0.5950],
         [-0.4306,  1.1761]],

        [[-1.8419,  0.5208],
         [-0.4928, -0.7707]],

        [[-0.3363, -1.4828],
         [ 1.0894, -0.0870]]])


In [66]:
x_t=torch.transpose(x,0,1)
print(x_t)

tensor([[[-1.3120, -0.5950],
         [-0.4306,  1.1761]],

        [[-1.8419,  0.5208],
         [-0.4928, -0.7707]],

        [[-0.3363, -1.4828],
         [ 1.0894, -0.0870]]])


In [69]:


# create a 3D tensor
A = torch.tensor([[[1,2,3],[3,4,5],[6,7,8]],
   [[5,6,7],[1,2,2],[8,9,10]],
   [[1,2,4],[1,2,5],[11,12,13]]])
print("Original Tensor A:\n",A)
print("Size of tensor:",A.size())

# print(A.t()) --> Error
# compute the transpose of the tensor
transposeA = torch.transpose(A, 0,1)
# other way to compute the transpose
# transposeA = A.transpose(0,1)

print("Transposed Tensor:\n",transposeA)
print("Size after transpose:",transposeA.size())

Original Tensor A:
 tensor([[[ 1,  2,  3],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 5,  6,  7],
         [ 1,  2,  2],
         [ 8,  9, 10]],

        [[ 1,  2,  4],
         [ 1,  2,  5],
         [11, 12, 13]]])
Size of tensor: torch.Size([3, 3, 3])
Transposed Tensor:
 tensor([[[ 1,  2,  3],
         [ 5,  6,  7],
         [ 1,  2,  4]],

        [[ 3,  4,  5],
         [ 1,  2,  2],
         [ 1,  2,  5]],

        [[ 6,  7,  8],
         [ 8,  9, 10],
         [11, 12, 13]]])
Size after transpose: torch.Size([3, 3, 3])


In [70]:
# Unsqueeze

'''
6.6. torch.unsqueeze - Returns a new tensor with a dimension of size one inserted at the specified position.
        - input (Tensor) – the input tensor
        - dim (int) – the index at which to insert the singleton dimension
        - out (Tensor, optional) – the output tensor
'''
# create a tensor
T = torch.Tensor([1,2,3]) # size 3
print("Original Tensor T:\n", T )
print("Size of T:", T.size())

# Squeeze the tensor in dimension o or column dim
unsqueezed_T = torch.unsqueeze(T, dim = 0) # now size 1x3
print("Unsqueezed T\n:", unsqueezed_T )
print("Size of UnSqueezed T:", unsqueezed_T.size())

# Squeeze the tensor in dimension 1 or row dim
unsqueezed_T = torch.unsqueeze(T, dim = 1) # now size 3x1
print("Unsqueezed T\n:", unsqueezed_T )
print("Size of Unsqueezed T:", unsqueezed_T.size())

Original Tensor T:
 tensor([1., 2., 3.])
Size of T: torch.Size([3])
Unsqueezed T
: tensor([[1., 2., 3.]])
Size of UnSqueezed T: torch.Size([1, 3])
Unsqueezed T
: tensor([[1.],
        [2.],
        [3.]])
Size of Unsqueezed T: torch.Size([3, 1])


In [71]:
x_t = torch.tensor([1, 2, 3, 4])
x_t_unsqueezed = torch.unsqueeze(x_t, dim=1)

print("Initial size: ", x_t.size())
print("Final size: ", x_t_unsqueezed.size())

Initial size:  torch.Size([4])
Final size:  torch.Size([4, 1])


In [75]:
# Normal random number

'''
7.1. torch.normal - Returns a tensor of random numbers drawn from separate normal distributions 
        whose mean and standard deviation are given.
            - mean (Tensor) – the tensor of per-element means
            - std (Tensor) – the tensor of per-element standard deviations
            - out (Tensor, optional) – the output tensor

'''
mean=torch.arange(1., 11.)
print(mean)
std=torch.arange(1, 0, -0.1)
print(std)
normal_random_tensor = torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))
print("normal_random_tensor = ", normal_random_tensor)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000])
normal_random_tensor =  tensor([1.2555, 1.4579, 3.3935, 3.5416, 4.7240, 5.7262, 6.2654, 7.9027, 9.0493,
        9.8945])


In [76]:
# Random num

'''
7.2. torch.rand - Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)
        - sizes (int...) – a sequence of integers defining the shape of the output tensor. 
            Can be a variable number of arguments or a collection like a list or tuple.
'''
x_rand=torch.rand(2,3)
print(x_rand)

tensor([[0.5215, 0.5970, 0.3795],
        [0.5428, 0.6996, 0.0676]])


In [77]:
# Random Integer

'''
7.3. torch.randint - Returns a tensor filled with random integers generated uniformly between low 
    (inclusive) and high (exclusive).
        - low (int, optional) – Lowest integer to be drawn from the distribution. Default: 0.
        - high (int) – One above the highest integer to be drawn from the distribution.
        - size (tuple) – a tuple defining the shape of the output tensor.
        - out (Tensor, optional) – the output tensor
        - dtype - Data type.
'''
x_randint=torch.randint(low=-10, high=10, size=(3,2))
print(x_randint)

tensor([[-9, -4],
        [-1,  1],
        [-7,  5]])


In [78]:
# Random normal

'''
7.4. torch.randn - Returns a tensor filled with random numbers from a normal distribution with 
    mean 0 and variance 1 (also called the standard normal distribution).
        - sizes (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.
        - out (Tensor, optional) – the output tensor
        - dtype - Data type.
'''
x_randn=torch.randn(2,3)
print(x_randn)

tensor([[ 0.5060, -0.5665, -0.5056],
        [ 0.9543, -0.0625, -0.8260]])


In [79]:
# Saving a tensor

'''
8.1. torch.save - Saves an object to a disk file.
        - obj – saved object
        - f – a file-like object (has to implement write and flush) or a string containing a file name
        - pickle_module – module used for pickling metadata and objects
        - pickle_protocol – can be specified to override the default protocol

'''

x = torch.tensor([0, 1, 2, 3, 4])
torch.save(x, 'tensor.pt')

In [80]:
# Loading a saved tensor

'''
8.2. tensor.load - Loads an object saved with torch.save() from a file.
'''

x = torch.load('tensor.pt')
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([0, 1, 2, 3, 4])


In [81]:
# Adding and disabling gradient

'''
8.3. torch.no_grad()      - Disable grad
    torch.enable_grad()  - Enable grad
'''

x = torch.zeros(1, requires_grad=True)
print("x requires grad = ", x.requires_grad)

y = x*3
print("y requires grad = ", y.requires_grad)

with torch.no_grad():
    z = x * 2
print("z requires grad = ", z.requires_grad)

x requires grad =  True
y requires grad =  True
z requires grad =  False


In [82]:
# Checking if NAN value is there in tensor

'''
8.4. torch.is_nan - Returns a new tensor with boolean elements representing if each element is NaN or not.
'''

x_in = torch.tensor([1, float('nan'), 2])
x_out = torch.isnan(x_in)

print("x_in = ", x_in)
print("x_out = ", x_out)

x_in =  tensor([1., nan, 2.])
x_out =  tensor([False,  True, False])


In [83]:
# Set computation device

'''
8.5. torch.device


Ex
>>> torch.device('cuda:0')
device(type='cuda', index=0)

>>> torch.device('cpu')
device(type='cpu')

>>> torch.device('cuda')  # current cuda device
device(type='cuda')
'''

torch.device('cpu')

device(type='cpu')

In [84]:
# Profiling - 1

'''
8.6. torch.autograd.profiler.profile - Context manager that manages autograd profiler state and holds a summary of results.
        - enabled (bool, optional) – Setting this to False makes this context manager a no-op. Default: True.
        - use_cuda (bool, optional) – Enables timing of CUDA events as well using the cudaEvent API. 
            Adds approximately 4us of overhead to each tensor operation. 
'''

x = torch.randn((1, 1), requires_grad=True)
with torch.autograd.profiler.profile() as prof:
    y = x ** 2
    y.backward()

print(prof)

-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                              aten::pow        78.70%      28.565ms        84.01%      30.492ms      30.492ms             1  
                                      aten::result_type         5.31%       1.926ms         5.31%       1.926ms       1.926ms             1  
                                               aten::to         0.00%       1.000us         0.00%       1.000us       1.000us             1  
                                        aten::ones_like         0.12%      44.000us         1.66%     603.000us     603.000us             1  
      