In [1]:
import os
import sys
import torch
import numpy as np

In [5]:
#Add
"""
1.1 torch.add - Adds the scalar value to each element of the input input and returns a new resulting tensor.
"""
x_in=torch.randn(4)
scaler=30
x_out=torch.add(x_in, scaler)
print("Way - 1")
print("x_in = ", x_in)
print("x_out = ", x_out)

'''
1.2. torch.add - Each element of the tensor other is multiplied by the scalar value and added to each element 
    of the tensor input. The resulting tensor is returned.
    out=input+value×other
        - input (Tensor) – the first input tensor
        - value (Number) – the scalar multiplier for other
        - other (Tensor) – the second input tensor
    
'''
x_in=torch.randn(4)
x_other=torch.randn(4)
value=10
x_out=torch.add(x_in, value, x_other)
print("Way - 2")
print("x_in = ", x_in)
print("x_other", x_other)
print("x_out = ", x_out)

Way - 1
x_in =  tensor([ 0.7376,  0.1039, -0.5643,  0.0250])
x_out =  tensor([30.7376, 30.1039, 29.4357, 30.0250])
Way - 2
x_in =  tensor([-0.3152,  0.5241,  0.0039, -0.4869])
x_other tensor([-0.6458,  0.1003,  0.8961, -0.1272])
x_out =  tensor([-6.7736,  1.5268,  8.9653, -1.7593])


In [8]:
# AddCDivide

'''
1.2. torch.addcdiv - out_i= tensor_i + value × [tensor_1]/[tensor_2]
    - tensor (Tensor) – the tensor to be added
    - value (Number, optional) – multiplier for tensor1./tensor2
    - tensor1 (Tensor) – the numerator tensor
    - tensor2 (Tensor) – the denominator tensor
    - out (Tensor, optional) – the output tensor
'''
x_in=torch.randn(1,3)
x_in

tensor([[-1.9441,  0.1587, -1.1047]])

In [9]:
x_1=torch.randn(3,1)
x_1

tensor([[-0.5574],
        [-0.3031],
        [ 0.3834]])

In [10]:
x_2=torch.randn(1,3)
x_2

tensor([[-0.9731, -1.5762, -0.3499]])

In [13]:
x=x_1/x_2
x

tensor([[ 0.5728,  0.3537,  1.5932],
        [ 0.3115,  0.1923,  0.8662],
        [-0.3940, -0.2432, -1.0957]])

In [14]:
0.1*x

tensor([[ 0.0573,  0.0354,  0.1593],
        [ 0.0311,  0.0192,  0.0866],
        [-0.0394, -0.0243, -0.1096]])

In [15]:
x_out=torch.addcdiv(x_in, 0.1,x_1,x_2)
print(x_out)

tensor([[-1.8868,  0.1941, -0.9454],
        [-1.9130,  0.1779, -1.0181],
        [-1.9835,  0.1344, -1.2143]])


In [ ]:
# # AddCMul

'''
1.3. torch.addcmul - out_i= tensor_i + value × [tensor_1]*[tensor_2]
'''
