In [1]:
import os
import sys
import torch
import numpy as np

In [5]:
#Add
"""
1.1 torch.add - Adds the scalar value to each element of the input input and returns a new resulting tensor.
"""
x_in=torch.randn(4)
scaler=30
x_out=torch.add(x_in, scaler)
print("Way - 1")
print("x_in = ", x_in)
print("x_out = ", x_out)

'''
1.2. torch.add - Each element of the tensor other is multiplied by the scalar value and added to each element 
    of the tensor input. The resulting tensor is returned.
    out=input+value×other
        - input (Tensor) – the first input tensor
        - value (Number) – the scalar multiplier for other
        - other (Tensor) – the second input tensor
    
'''
x_in=torch.randn(4)
x_other=torch.randn(4)
value=10
x_out=torch.add(x_in, value, x_other)
print("Way - 2")
print("x_in = ", x_in)
print("x_other", x_other)
print("x_out = ", x_out)

Way - 1
x_in =  tensor([ 0.7376,  0.1039, -0.5643,  0.0250])
x_out =  tensor([30.7376, 30.1039, 29.4357, 30.0250])
Way - 2
x_in =  tensor([-0.3152,  0.5241,  0.0039, -0.4869])
x_other tensor([-0.6458,  0.1003,  0.8961, -0.1272])
x_out =  tensor([-6.7736,  1.5268,  8.9653, -1.7593])


In [8]:
# AddCDivide

'''
1.2. torch.addcdiv - out_i= tensor_i + value × [tensor_1]/[tensor_2]
    - tensor (Tensor) – the tensor to be added
    - value (Number, optional) – multiplier for tensor1./tensor2
    - tensor1 (Tensor) – the numerator tensor
    - tensor2 (Tensor) – the denominator tensor
    - out (Tensor, optional) – the output tensor
'''
x_in=torch.randn(1,3)
x_in

tensor([[-1.9441,  0.1587, -1.1047]])

In [9]:
x_1=torch.randn(3,1)
x_1

tensor([[-0.5574],
        [-0.3031],
        [ 0.3834]])

In [10]:
x_2=torch.randn(1,3)
x_2

tensor([[-0.9731, -1.5762, -0.3499]])

In [13]:
x=x_1/x_2
x

tensor([[ 0.5728,  0.3537,  1.5932],
        [ 0.3115,  0.1923,  0.8662],
        [-0.3940, -0.2432, -1.0957]])

In [14]:
0.1*x

tensor([[ 0.0573,  0.0354,  0.1593],
        [ 0.0311,  0.0192,  0.0866],
        [-0.0394, -0.0243, -0.1096]])

In [15]:
x_out=torch.addcdiv(x_in, 0.1,x_1,x_2)
print(x_out)

tensor([[-1.8868,  0.1941, -0.9454],
        [-1.9130,  0.1779, -1.0181],
        [-1.9835,  0.1344, -1.2143]])


In [ ]:
# # AddCMul

'''
1.3. torch.addcmul - out_i= tensor_i + value × [tensor_1]*[tensor_2]
'''


# Roadmap 2 - Mathematical operations


1.1.   torch.add     - Adds the scalar value to each element of the input input
1.2.   torch.addcdiv - out_i= tensor_i + value × [tensor_1]/[tensor_2]
1.3.   torch.addcmul - out_i= tensor_i + value × [tensor_1]*[tensor_2]
1.4.   torch.div     - Divides each element of the input input with the scalar value
1.5.   torch.mul     - Multiples each element of the input input with the scalar value


2.1.   torch.ceil    - Returns a new tensor with the ceil of the elements of input, the smallest integer
                          greater than or equal to each element.
2.2.   torch.clamp   - Clamp all elements in input into the range [ min, max ] and return a resulting tensor
2.3.   torch.floor   - Returns a new tensor with the floor of the elements of input, the largest integer less 
                          than or equal to each element.
2.4.   torch.round   - Returns a new tensor with each of the elements of input rounded to the closest integer.
2.5.   torch.trunc   - Returns a new tensor with the truncated integer values of the elements of input


3.1.   torch.asin    - Returns a new tensor with the arcsine of the elements of input
3.2.   torch.acos    - Returns a new tensor with the arccosine of the elements of input
3.3.   torch.atan    - Returns a new tensor with the arctangent of the elements of input
3.4.   torch.atan2   - Returns a new tensor with the arctangent of the elements of input1 and input2.
3.5.   torch.cos     - Returns a new tensor with the cosine of the elements of input
3.6.   torch.sin     - Returns a new tensor with the Sine of the elements of input
3.7.   torch.tan     - Returns a new tensor with the Tangent of the elements of input
3.8.   torch.cosh    - Returns a new tensor with the hyperbolic cosine of the elements of input
3.9.   torch.sinh    - Returns a new tensor with the hyperbolic sine of the elements of input
3.10.  torch.tanh    - Returns a new tensor with the Hyperbolic Tangent of the elements of input


4.1.   torch.argmax   - Returns the indices of the maximum values of a tensor across a dimension.
4.2.   torch.argmin   - Returns the indices of the minimum values of a tensor across a dimension.
4.3.   torch.mean     - Returns the mean value of all elements in the input tensor.
4.4.   torch.median   - Returns the median value of all elements in the input tensor.
4.5.   torch.mode     - Returns the mode value of all elements in the input tensor.
4.6.   torch.prod     - Returns the product of all elements in the input tensor.
4.7.   torch.std      - Returns the standard deviation value of all elements in the input tensor.
4.8.   torch.sum      - Returns the sum of all elements in the input tensor.
4.9.   torch.var      - Returns the variance of all elements in the input tensor.


5.1.   torch.erf      - Computes the error function of each element.
5.2.   torch.erfc     - Computes the complementary error function of each element. 
5.3.   torch.erfinv   - Computes the inverse error function of each element.
5.4.   torch.exp      - Returns a new tensor with the exponential of the elements of input
5.5.   torch.expm1    - Returns a new tensor with the exponential of the elements minus 1 of input
5.6.   torch.fmod     - Computes the element-wise remainder of division.
5.7.   torch.abs      - Computes the element-wise absolute value of the given input tensor.
5.8.   torch.frac     - Computes the fractional portion of each element in tensor
5.9.   torch.log      - Returns a new tensor with the logarithm of the elements. Base of log - e
5.10.  torch.log10    - Returns a new tensor with the logarithm of the elements. Base of log - 10
5.11.  torch.log1p    - Returns a new tensor with the logarithm of the elements (1 + input).
5.12.  torch.log2     - Returns a new tensor with the logarithm of the elements of input. Base of log - 2
5.13.  torch.neg      - Returns a new tensor with the negative of the elements of input
5.14.  torch.pow      - Takes the power of each element in input with exponent.
5.15.  torch.reciprocal - Returns a new tensor with the reciprocal of the elements of input
5.16.  torch.rsqrt    - Returns a new tensor with the reciprocal of the square-root of each element.
5.17.  torch.sigmoid  - Returns a new tensor with the sigmoid of the elements of input
5.18.  torch.sign     - Returns a new tensor with the sign of the elements of input.
5.19.  torch.sqrt     - Returns a new tensor with the square-root of each of the elements of input.
5.20.  torch.norm     - Returns the normalized value of all elements in the input tensor.


6.1.   torch.eq      - Computes element-wise equality
6.2.   torch.ge      - Computes element-wise greater-than-equality
6.3.   torch.gt      - Computes element-wise greater-than function
6.4.   torch.le      - Computes element-wise less-than-equality
6.5.   torch.lt      - Computes element-wise less-than function
6.6.   torch.max     - Returns the maximum value of all elements in the input tensor.
6.7.   torch.min     - Returns the minimum value of all elements in the input tensor.


7.1.   torch.cumprod   - Returns the cumulative product of elements of input in the dimension dim.
7.2.   torch.cumsum    - Returns the cumulative sum of elements of input in the dimension dim.
7.3.   torch.logsumexp - Returns the log of summed exponentials of each row of the input tensor in the 
                            given dimension dim
7.4.   torch.einsum    - This function provides a way of computing multilinear expressions using the Einstein  
                            summation convention.
7.5.   torch.histc     - Computes the histogram of a tensor.


8.1.   torch.unique    - Returns the unique scalar elements of the input tensor as a 1-D tensor.
8.2.   torch.sort      - Sorts the elements of the input tensor.
8.3.   torch.topk      - Returns the k largest elements of the given input tensor along a given dimension.
8.4.   torch.bincount  - Count the frequency of each value in an array of non-negative ints.
8.5.   torch.trace     - Returns the sum of the elements of the diagonal of the input 2-D matrix.
8.6.   torch.tril      - Returns the lower triangular part of the matrix (2-D tensor) input
8.7.   torch.triu      - Returns the upper triangular part of the matrix (2-D tensor) input


9.1.   torch.lerp      - Does a linear interpolation of two tensors start and end based on a scalar weight and 
                           returns the resulting out tensor.              
9.2.   torch.dist      - Returns the lp-norm of (input - other)
9.3.   torch.fft       - Complex-to-complex Discrete Fourier Transform
9.4.   torch.ifft      - Complex-to-complex Inverse Discrete Fourier Transform
9.5.   torch.stft      - Short time fourier transform 
9.6.   torch.cross     - Returns the cross product of vectors in dimension dim of input and other
9.7.   torch.diag      - If input is a vector (1-D tensor), then returns a 2-D square tensor with the elements 
                          of input as the diagonal. If input is a matrix (2-D tensor), then returns a 1-D tensor 
                          with the diagonal elements of input.


10.1.  torch.bartlett_window 
10.2.  torch.blacman_window
10.3.  torch.hamming_window
10.4.  torch.hann_window



In [4]:
# Add
'''
1.1 torch.add - Adds the scalar value to each element of the input input and returns a new resulting tensor.
'''
x_in=torch.randn(4)
x_in

tensor([ 2.6241, -0.2108, -0.6441, -0.9712])

In [5]:
scaler=30
x_out=torch.add(x_in, scaler)
x_out

tensor([32.6241, 29.7892, 29.3559, 29.0288])

In [6]:
x_in=torch.randn(2,3)
x_in

tensor([[ 0.9207, -0.1706,  0.9116],
        [ 0.5842,  0.3687,  0.7570]])

In [7]:
x_out=torch.add(x_in, scaler)
x_out

tensor([[30.9207, 29.8294, 30.9116],
        [30.5842, 30.3687, 30.7570]])

In [8]:
x_in=torch.randn(4)
x_in

tensor([-1.3071, -0.5991,  0.0778,  0.1830])

In [11]:
x_other=torch.randn(4,1)
x_other

tensor([[1.0581],
        [0.4151],
        [0.2630],
        [0.3831]])

In [14]:
val=10
x_out=torch.add(x_in,val, x_other)
x_out

tensor([[ 9.2737,  9.9817, 10.6587, 10.7639],
        [ 2.8434,  3.5514,  4.2284,  4.3336],
        [ 1.3233,  2.0313,  2.7082,  2.8134],
        [ 2.5241,  3.2320,  3.9090,  4.0142]])

In [13]:
x_out=torch.add(x_in, x_other, val)
x_out

TypeError: add() takes 2 positional arguments but 3 were given

In [15]:
x_in

tensor([-1.3071, -0.5991,  0.0778,  0.1830])

In [16]:
x_other

tensor([[1.0581],
        [0.4151],
        [0.2630],
        [0.3831]])

In [17]:
val

10

In [19]:
torch.add(x_in,val,x_other)

tensor([[ 9.2737,  9.9817, 10.6587, 10.7639],
        [ 2.8434,  3.5514,  4.2284,  4.3336],
        [ 1.3233,  2.0313,  2.7082,  2.8134],
        [ 2.5241,  3.2320,  3.9090,  4.0142]])

In [20]:
# AddCDivide
'''
1.2. torch.addcdiv - out_i= tensor_i + value × [tensor_1]/[tensor_2]
    - tensor (Tensor) – the tensor to be added
    - value (Number, optional) – multiplier for tensor1./tensor2
    - tensor1 (Tensor) – the numerator tensor
    - tensor2 (Tensor) – the denominator tensor
    - out (Tensor, optional) – the output tensor
'''
x_in=torch.randn(1,3)
x_in

tensor([[-1.4876,  0.6654, -0.7630]])

In [21]:
x_1=torch.randn(3,1)
x_1

tensor([[-0.1049],
        [ 0.2768],
        [-0.0074]])

In [22]:
x_2=torch.randn(1,3)
x_2

tensor([[-1.2912, -0.2036,  0.1769]])

In [23]:
x_out=torch.addcdiv(x_in, 0.1, x_1,x_2)
x_out

tensor([[-1.4795,  0.7170, -0.8223],
        [-1.5090,  0.5295, -0.6066],
        [-1.4870,  0.6691, -0.7672]])

In [26]:
x_in+0.1*(x_1/x_2)

tensor([[-1.4795,  0.7170, -0.8223],
        [-1.5090,  0.5295, -0.6066],
        [-1.4870,  0.6691, -0.7672]])

In [27]:
# AddCMul
'''
1.3. torch.addcmul - out_i= tensor_i + value × [tensor_1]*[tensor_2]
'''
x_in=torch.randn(1,3)
x_in

tensor([[-0.3138, -0.5772,  1.8656]])

In [28]:
x_1=torch.randn(1,3)
x_1

tensor([[ 1.3961, -0.8398,  0.0346]])

In [29]:
x_2=torch.randn(3,1)
x_2

tensor([[ 2.1762],
        [-0.4850],
        [-1.1243]])

In [30]:
x_out=torch.addcmul(x_in, 0.1, x_1,x_2)
x_out

tensor([[-0.0100, -0.7599,  1.8731],
        [-0.3815, -0.5364,  1.8639],
        [-0.4708, -0.4827,  1.8617]])

In [31]:
x_1

tensor([[ 1.3961, -0.8398,  0.0346]])

In [32]:
x_2

tensor([[ 2.1762],
        [-0.4850],
        [-1.1243]])

In [33]:
x_2*x_1

tensor([[ 3.0382, -1.8276,  0.0753],
        [-0.6771,  0.4073, -0.0168],
        [-1.5696,  0.9442, -0.0389]])

In [36]:
x_1*x_2# dot product

tensor([[ 3.0382, -1.8276,  0.0753],
        [-0.6771,  0.4073, -0.0168],
        [-1.5696,  0.9442, -0.0389]])

In [37]:
x_1@x_2# matrix multiplication

tensor([[3.4066]])

In [38]:
#Div
'''
1.4 torch.div - Divides each element of the input input with the scalar value and returns a new resulting tensor.
'''
x_in=torch.randn(4)
x_in

tensor([-0.5417, -1.4136, -2.3911,  1.4485])

In [39]:
scaler=4
x_out=torch.div(x_in,scaler)
x_out

tensor([-0.1354, -0.3534, -0.5978,  0.3621])

In [40]:
x_in=torch.randn(4)
x_in

tensor([-0.8460,  0.4762,  1.5465,  1.8373])

In [41]:
x_other=torch.randn(4)
x_other

tensor([-0.9462, -0.4036, -1.7217,  0.1409])

In [42]:
val=10

In [44]:
x_out=torch.div(x_in, x_other)
x_out

tensor([ 0.8941, -1.1799, -0.8983, 13.0353])

In [45]:
# Mul
'''
1.5 torch.mul - Multiples each element of the input input with the scalar value and returns a new resulting tensor.
'''
x_in=torch.randn(4)
scaler=4
x_out=torch.mul(x_in,scaler)
x_out

tensor([-2.6179,  2.5543, -0.5026, -0.3362])

In [46]:
# CEIL
'''
2.1. torch.ceil - Returns a new tensor with the ceil of the elements of input, 
    the smallest integer greater than or equal to each element.
'''
x_in=torch.randn(5)
x_in

tensor([ 2.5740, -0.8288,  1.6461, -1.8953, -0.5230])

In [47]:
x_out=torch.ceil(x_in)
x_out

tensor([ 3., -0.,  2., -1., -0.])

In [48]:
#CLAMP
'''
2.2. torch.clamp - Clamp all elements in input into the range [ min, max ] and return a resulting tensor
        - input (Tensor) – the input tensor
        - min (Number) – lower-bound of the range to be clamped to
        - max (Number) – upper-bound of the range to be clamped to
        - out (Tensor, optional) – the output tensor
'''
x_in=torch.randn(8)
x_in

tensor([-1.5046,  1.1580, -1.2041,  0.9910, -1.2664,  0.8861,  0.3264, -0.3836])

In [49]:
x_out=torch.clamp(x_in, min=-0.5, max=0.5)
x_out

tensor([-0.5000,  0.5000, -0.5000,  0.5000, -0.5000,  0.5000,  0.3264, -0.3836])

In [50]:
x_in=torch.randn(8,2)
x_in

tensor([[ 0.2884,  0.4322],
        [-0.5761,  0.1894],
        [ 0.3716,  0.3805],
        [ 1.3771, -0.2426],
        [ 1.8854, -0.6692],
        [-0.8141, -0.6669],
        [ 0.0328, -0.0754],
        [ 0.7670,  0.2208]])

In [52]:
x_out=torch.clamp(x_in,min=-0.5,max=0.5)
x_out

tensor([[ 0.2884,  0.4322],
        [-0.5000,  0.1894],
        [ 0.3716,  0.3805],
        [ 0.5000, -0.2426],
        [ 0.5000, -0.5000],
        [-0.5000, -0.5000],
        [ 0.0328, -0.0754],
        [ 0.5000,  0.2208]])

In [59]:
min1=torch.linspace(-1,1,steps=10)
min1

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [58]:
x_out=torch.clamp(x_in, min=min1)
x_out

tensor([[ 0.2884,  1.0000],
        [-0.5761,  1.0000],
        [ 0.3716,  1.0000],
        [ 1.3771,  1.0000],
        [ 1.8854,  1.0000],
        [-0.8141,  1.0000],
        [ 0.0328,  1.0000],
        [ 0.7670,  1.0000]])

In [60]:
#FLOOR
'''
2.3. torch.floor - Returns a new tensor with the floor of the elements of input, 
        the largest integer less than or equal to each element.
'''
x_in=torch.randn(4)
x_in

tensor([ 0.1546, -0.6641,  1.2238,  2.0900])

In [61]:
x_out=torch.floor(x_in)
x_out

tensor([ 0., -1.,  1.,  2.])

In [62]:
# Round
'''
2.4. torch.round - Returns a new tensor with each of the elements of input rounded to the closest integer.
'''
x_in=torch.randn(4)
print(x_in)
x_out=torch.round(x_in)
x_out

tensor([-1.4905, -0.7229,  0.1941, -0.2170])


tensor([-1., -1.,  0., -0.])

In [63]:
#Truncating
x_in=torch.randn(4)
x_in

tensor([ 1.3124, -1.3386, -0.7836, -0.8634])

In [65]:
x_out=torch.trunc(x_in)
x_out

tensor([ 1., -1., -0., -0.])

In [66]:
#Argmax
x_in=torch.randn(5)
x_in

tensor([-0.6707,  0.0523, -0.0293, -1.1485, -0.8968])

In [67]:
x_out=torch.argmax(x_in)
x_out

tensor(1)

In [68]:
#Argmin
x_in=torch.randn(8)
x_in

tensor([ 0.0238, -1.0564,  0.2107,  0.8722, -0.1272,  0.0229,  1.0044,  0.4553])

In [69]:
x_out=torch.argmin(x_in)
x_out

tensor(1)

In [70]:
a=torch.randn(4,4)
a

tensor([[ 1.7744,  1.8698, -0.5797, -0.0328],
        [ 1.1152, -0.0270, -1.6175,  0.5801],
        [ 0.7528,  0.1008, -0.0489, -0.7621],
        [-1.5500, -1.9371, -1.8206, -0.2238]])

In [71]:
out=torch.argmax(a, dim=1)
out

tensor([1, 0, 0, 3])

In [72]:
out1=torch.argmin(a,dim=1)
out1

tensor([2, 2, 3, 1])

In [73]:
out1=torch.argmin(a,dim=0)
out1

tensor([3, 3, 3, 2])

In [4]:
a=torch.randn(6)
a

tensor([-0.2105,  2.2926,  1.1594,  0.0409,  0.0381, -0.6679])

In [5]:
out=torch.clamp(a,min=0.5, max=0.9)
print(out)

tensor([0.5000, 0.9000, 0.9000, 0.5000, 0.5000, 0.5000])


In [6]:
a=torch.FloatTensor([1,4,6,8,10,14])
a

tensor([ 1.,  4.,  6.,  8., 10., 14.])

In [7]:
out=torch.clamp(a, min=5,max=10)
print(out)

tensor([ 5.,  5.,  6.,  8., 10., 10.])


In [8]:
a=torch.randint(low=0, high=10, size=(10,1))
print(a)

tensor([[9],
        [4],
        [0],
        [6],
        [5],
        [0],
        [2],
        [1],
        [9],
        [4]])


In [9]:
a=torch.clamp(a, 3,9)
a

tensor([[9],
        [4],
        [3],
        [6],
        [5],
        [3],
        [3],
        [3],
        [9],
        [4]])

In [11]:
#Compute mean
'''
4.3. torch.mean - Returns the mean value of all elements in the input tensor.
'''
x_in=torch.tensor([1.,2.,3.,4.,5.])
x_out=torch.mean(x_in)
x_out

tensor(3.)

In [14]:
# Computer median
x_in=torch.tensor([1.,2.,3.,4.,5.,1.])
x_out=torch.median(x_in)
print(x_out)

tensor(2.)
